Context for docs
datanav/docs pull request #111
Opened 2020-06-22 06:34 UTC by mariebeersangvig

PR for improvements to Docs. Contains more examples, more context and more explanations and definitions.

2020-07-11 08:30 UTC, TarjeiSkrede commented on best-practice.rst
> +The data fed into Sesam through **input pipes** where namespaced identity is added in order to keep existing data model with joins intact. In addition **RDF type** for future filtering and classifica
"The data is fed into.."

2020-07-11 08:31 UTC, TarjeiSkrede commented on best-practice.rst
> +The data fed into Sesam through **input pipes** where namespaced identity is added in order to keep existing data model with joins intact. In addition **RDF type** for future filtering and classifica
"In addtion is a **RDF type** added in the input pipe for future filtering and classification."

2020-07-11 08:38 UTC, TarjeiSkrede commented on best-practice.rst
> +**Preparation pipes** is where **global datasets** are prepared for target systems. It is here most of logic is added. It could include enriching with more context from other datasets, structuring da
"It is here most of the logic is added."

2020-07-11 08:44 UTC, TarjeiSkrede commented on best-practice.rst
> +**Output pipes** has no logic and basically sends data to endpoint.
"**Output pipes** basically sends data to an endpoint and should normally have no logic."

2020-08-26 07:51 UTC, ashkanvahidishams requested changes

2020-08-26 07:51 UTC, ashkanvahidishams commented on best-practice.rst
> +**Preparation pipes** is where **global datasets** are prepared for target systems. It is here most of the logic is added. It could include enriching with more context from other datasets, structurin
explanation for why we do the transforms here would be nice.

2020-08-26 07:51 UTC, ashkanvahidishams commented on best-practice.rst
> +**Output pipes** basically sends data to an endpoint and should normally have no logic.
same here.

2020-08-26 07:51 UTC, ashkanvahidishams commented on best-practice.rst
> + }dc
?

2020-08-26 07:51 UTC, ashkanvahidishams commented on getting-started.rst
> +  ["hops", {
kan hende, siden den mangler ytterste nivå som feks add, så blir det litt komplisert å forstå hvordan denne fungerer.

2020-08-26 07:51 UTC, ashkanvahidishams commented on getting-started.rst
> +  ["hops", {
eller vil denne fungere i det heletatt som outputen litt ned beskriver?

2020-08-26 07:51 UTC, ashkanvahidishams commented on getting-started.rst
> +Final part is the actual program. FOr this we create a python file, also in the "service" folder, named "DemoMicroservice.py" with the following code:
FOr

2020-08-26 08:23 UTC, ashkanvahidishams approved these changes

2020-08-26 08:30 UTC, merged