'#208: Adding Pipe-shortcuts 3.1'
datanav/docs pull request #216
Opened 2021-03-25 09:06 UTC by JonasAls89

2021-03-25 12:08 UTC, ga-hegsvold reviewed
There are different shortcuts for Mac vs Windows/Linux. Maybe include both?

2021-03-25 12:11 UTC, ga-hegsvold commented on training/030_dtl/020_Beginner.rst
> +
I think it would be good to also include the shortcut for Replace (Ctrl+h) and maybe add a remark that hitting Ctrl+f twice will also take you to the replace dialog.

2021-03-26 06:24 UTC, gabriellsesam commented
Good points from Gah here. I would also like to see a small reference to the "Editor Options" button on the Pipe config page as this will show the user all available shortcuts on the fly.

![Screenshot 2021-03-26 at 07 22 36](https://user-images.githubusercontent.com/46919496/112591132-2d8a8c00-8e04-11eb-8a9e-5d3e140eb901.png)

2021-03-26 06:25 UTC, gabriellsesam requested changes
See previous comments

2021-03-30 10:57 UTC, JonasAls89 commented
ctrl+h does not seem to be working on MacOS GAH, so I didn't add it. Maybe we can discuss it during our next meeting.

2021-03-30 11:28 UTC, ga-hegsvold requested changes
Just a follow-up on the Replace shortcut.

2021-03-30 11:28 UTC, ga-hegsvold commented on training/030_dtl/020_Beginner.rst
> +
@JonasAls89 It's probably Cmd+h on MacOS. Could you please check and report it as a bug to support if it does not work?

I tried hitting Ctrl+f twice now to activate Search-Replace and that did not work. I've reported that to support.

2021-03-30 11:31 UTC, JonasAls89 commented
mh, no cmd+h minimises your browser window on MAC... 🤷‍♂️

2021-03-30 11:51 UTC, ga-hegsvold approved these changes

2021-04-09 06:53 UTC, gabriellsesam approved these changes

2021-04-09 06:53 UTC, merged