#196: Edit Architecture: Beginner: Different types of Architectures
datanav/docs pull request #219
Opened 2021-03-26 07:22 UTC by gabriellsesam

Please give feedback on my edit of this topic.
Some things to question on this pr:
* Is the intent of what you wrote intact after my edit?
* Do the changes make sense?
* Is there something you would like to see added or removed?

2021-03-30 11:12 UTC, JonasAls89 requested changes
Lines 14-15 shifts the meaning compared to what I intended. In addition, I think the wording on line 15 is suboptimal.

Line 17-18: I don't think it's correct to say: "we want to lay the foundation...". I would rephrase.

Line 25: Are you sure it's the simplest integration principle? 

Line 29: It's more consistent to write system A and system B.

Line 30: Typo: "threshold"

Line 81: I dont think it's correct to state: "these systems store".. store is not necessarily what DDA focuses on.

Line 96-97: I think you have to add "albeit flexible", as robust and flexible contradicts one another.

Line 104: Does not make sense. Needs to be rewritten.

2021-03-30 12:15 UTC, gabriellsesam commented
> Lines 14-15 shifts the meaning compared to what I intended. In addition, I think the wording on line 15 is suboptimal.
> 

Data is not by itself mobile and would therefore be inprecice to say that DDA. DDA gives data mobility, not the other way around. However, I think we can keep this point somehow by reprhasing as:
`Recently Data Driven Architecture has mobilized data in new ways by placing data and its meaning at it's center.`

> Line 17-18: I don't think it's correct to say: "we want to lay the foundation...". I would rephrase.
> 

The edit says lay out the history, but we could rephrase it like
`To show the evolution of Integration Architectures and why Data Driven Architecture is the natural step forward, we will first introduce you to P2P and ESB.`

> Line 25: Are you sure it's the simplest integration principle?
> 

Yes, as in math a point is the simplest type of object based on amount of properties to contend with. A line would just be a connection of two points (P2P)- which in turn is simpler than a triangle, rectangle and so on.

> Line 29: It's more consistent to write system A and system B.
> 

agree

> Line 30: Typo: "threshold"
> 

threefold is correct here, as we go from 1 to 3 connections by adding system C.

> Line 81: I don't think it's correct to state: "these systems store".. store is not necessarily what DDA focuses on.
> 

I'm not sure what you mean as the new phrasing does not say we store the data, but rather focus on the data which these systems store instead of focusing on the system itself. I think it is more precise.

> Line 96-97: I think you have to add "albeit flexible", as robust and flexible contradicts one another.
> 

Can be rephrased to `you need logical and robust principles to create flexible data flows and models`

> Line 104: Does not make sense. Needs to be rewritten.

We can remove line 102-104

2021-05-05 07:26 UTC, JonasAls89 approved these changes

2021-05-12 12:05 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
> +as we go from 1 integration between System A and System B to 3 integrations.
La dette til under "Semantisk Veiledning" i onenote / Kursutvikling/ Retningslinjer

2021-05-12 14:36 UTC, ga-hegsvold approved these changes

2021-05-12 14:59 UTC, merged