#220: Edit: Architecture: Beginner: Datahub
datanav/docs pull request #221
Opened 2021-03-26 10:04 UTC by gabriellsesam

2021-03-30 11:24 UTC, JonasAls89 requested changes
Agree with these changes, aside from lines 119-122, I would keep the lines I wrote.

2021-05-05 07:25 UTC, JonasAls89 approved these changes

2021-05-12 09:58 UTC, ga-hegsvold requested changes

2021-05-12 09:58 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +exposing data to be retreived by the datahub. As such, a datahub mediates and
I wonder if some semantics are lost here by rephrasing "an external system" to "be retreived by the datahub"?

The rephrasing seems to focus on the datahub being the receiver of data, either by push (inject) or pull (retreive).
In the next sentence we talk about mediation between systems so I think it's important here to point out that the datahub also makes data available for consumption.

OR...
We could skip the entire sentence starting with "In practice...". I think the paragraph still would convey the message.

2021-05-12 11:01 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
>  A Datahub shares data by connecting generators of data with consumers of
Implemented.

2021-05-12 11:03 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +exposing data to be retreived by the datahub. As such, a datahub mediates and
Deleted the sentence as suggested

2021-05-12 11:28 UTC, ga-hegsvold approved these changes

2021-05-12 11:33 UTC, merged