#198: Formatting section 1.1.5
datanav/docs pull request #223
Opened 2021-03-31 07:29 UTC by erik-leven

Formatted figure, adde figure text and corrected format of _id

2021-03-31 13:14 UTC, ga-hegsvold requested changes
A couple of recommendations and questions.

2021-03-31 13:14 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +   *Figure 1.1.5A - A general pipeline flow in Sesam depicting the three central parts of a
Ideally, numbering of figures (and any other numbered sections/blocks) should be handled by the layout tool.
It's also preferable to give figures and other block constructs an identifier so that they can be referenced without having to know the exact numbering. The numbering can change as the document grows.
Is this possible to achieve with rst and the tool chain we currently have?

2021-03-31 13:14 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +|  **Systems**: A system’s main feature is to import and export data
Could this and the following paragraphs qualify as a definition list?
https://docutils.sourceforge.io/docs/user/rst/quickref.html#definition-lists

2021-04-08 10:29 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +|  **Systems**: A system’s main feature is to import and export data
Ok, I think your idea looks better. Fix is coming up

2021-04-08 10:30 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +   *Figure 1.1.5A - A general pipeline flow in Sesam depicting the three central parts of a
I have no idea. Maybe we should cover this on the meeting today

2021-04-08 10:35 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +   *Figure 1.1.5A - A general pipeline flow in Sesam depicting the three central parts of a
Or tomorrow? ;-) I don't see any booked meetings today.

2021-04-08 11:44 UTC, ga-hegsvold requested changes
I think the content and structure looks good. Just a minor typo.

2021-04-08 11:44 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +   Pipes handles the transformation of the data and specifies
Small typo: "Pipes handle**s** ..." should be "Pipes handle ..."

2021-04-09 06:25 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +   Pipes handles the transformation of the data and specifies
fixed

2021-04-09 06:40 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
>     into and out of the Sesam portal. They are therefore found in the
Systems are the interface we use to import and export data - but the pipes actually do the importing/exporting. We should be clear about that here

2021-04-09 06:42 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
>     which in turn can manipulate and delegate data according to your own
`directly to a database of simply send`
typo: of -> or

2021-04-09 06:44 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
> +   Pipes handle the transformation of the data and specifies
Pipes handle the transformation but pipes don't necessarily need to transform data. Their main function is to move data

2021-04-09 06:44 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
>     allows you to add, remove, transform and combine data according to
`transform and combine` -> `transform or combine`

2021-04-09 06:47 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
>     generally found between pipes. Sesam stores data in order to be able
```SQL database.  This is where pipes store the
data they produce unless a sink is specified.```
I think this is a clearer explanation

2021-04-09 06:49 UTC, gabriellsesam commented
The definition list looks very nice! Had some small comments but all in all very good

2021-04-09 08:23 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +   *Figure 1.1.5A - A general pipeline flow in Sesam depicting the three central parts of a
wise guy 🗡️

2021-04-09 08:34 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
>     generally found between pipes. Sesam stores data in order to be able
fixed and rewritten

2021-04-09 08:34 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
>     allows you to add, remove, transform and combine data according to
fixed

2021-04-09 08:34 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +   Pipes handle the transformation of the data and specifies
fixed and rewritten

2021-04-09 08:34 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
>     which in turn can manipulate and delegate data according to your own
fixed

2021-04-09 08:34 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
>     into and out of the Sesam portal. They are therefore found in the
fixed and rewritten

2021-04-09 11:47 UTC, gabriellsesam approved these changes
Veri nize

2021-04-09 12:10 UTC, ga-hegsvold requested changes
A couple of typos and suggestions.

2021-04-09 12:10 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +   into and out of the Sesam portal. The actual import and export is carried out by the pipes connected to the systems. The systems are  therefore found in the
Is the reference to "the Sesam portal" correct in this context? The Sesam portal is where we see all the Sesam nodes/instances we have access to. Maybe it would be more precise to say "... into and out of Sesam nodes."?

2021-04-09 12:10 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +   Pipes main functions are to actualize the import and export of data, to handle transformation of the data when needed as well as to specify
This is kind of nit-picky, but in the **Systems** section above, it says "A system's main ...".
I think it would be nice and consistent if the **Pipes** section has the same form: "A pipe's main ...".

2021-04-20 11:35 UTC, ga-hegsvold approved these changes

2021-04-20 11:45 UTC, merged