#200: Namegiving Conventions->Naming Conventions & Fix typos in text …
datanav/docs pull request #253
Opened 2021-04-15 06:51 UTC by gabriellsesam

…and image

2021-04-15 06:55 UTC, erik-leven approved these changes

2021-04-20 10:02 UTC, ga-hegsvold requested changes
A few comments and (mostly open) questions.

2021-04-20 10:02 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +
Would have liked to see these two following figures tagged as "examples", but not sure how/if that is supported by RST.
Anyone found a sensible way to do that yet?

2021-04-20 10:11 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Naming Conventions
Hmm, good point. Personally I'd say capitalize for titles, but not for prepositions or articles (i.e. a/an/the, on, at, for...)

2021-04-20 10:33 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
>  Input pipes should be named according to endpoint/table they connect to
Fixed

2021-04-20 10:35 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +
Not sure on how you wish that tag to be

2021-04-20 10:39 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
>  -  Localizing specific flows becomes easier.
done

2021-04-20 11:00 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Naming Conventions
Yeah, I agree. Consistency is more important that which form we pick.
@gabriellsesam Any preferences on this? Maybe we should discuss it in the next meeting?

2021-04-20 11:10 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +
It's more a question of what RST supports and how our/a tool chain can recognize it and handle it properly.
`<broken-record>`I would not be surprised if we at some point in the near future will see benefits of being able to show all our examples (and figures) listed with proper numbers and titles.`</broken-record>`

2021-04-20 11:17 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +
I'll resolve this for now, but I'm really keen to find out if this fesable with RST.

2021-04-21 06:43 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Naming Conventions
I think it makes sense to only capitalize the first word

2021-04-21 07:56 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Naming Conventions
It's also a bit easier to remember which words to capitalize if we only do it on the first word. 👴🏻

2021-04-27 06:39 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Naming Conventions
fixed

2021-04-27 07:45 UTC, gabriellsesam commented
Warning, treated as error:
/home/travis/build/datanav/docs/training/030_dtl/020_Beginner.rst:145: WARNING: undefined label: namegiving-conventions-1-1 (if the link has no caption the label must precede a section header)

2021-04-27 07:56 UTC, ga-hegsvold requested changes
I referenced this section in a previous commit:
training/030_dtl/020_Beginner.rst:146::ref:`namegiving-conventions-1-1`,
training/030_dtl/020_Beginner.rst:172::ref:`namegiving-conventions-1-1`

Could you please update these as well?

2021-05-12 11:21 UTC, ga-hegsvold approved these changes

2021-05-12 13:31 UTC, merged