#247 : adding generic inbound and outbound pipes section
datanav/docs pull request #256
Opened 2021-04-20 11:56 UTC by JonasAls89

2021-04-20 13:19 UTC, ga-hegsvold requested changes

2021-04-20 13:19 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +Generic inbound and outbound pipes
A comment on the term "Generic": This term is a bit misleading, I think. The first thing that came to mind when I saw this title was that this is about pipes that can be reused for different purposes. Generic as opposed to specific (with a specific purpose). But that's not what is meant here. This is more about why we recommend doing "raw"/"pure" imports into Sesam and to not start changing or make assumptions about the data this early in the flow, and to minimize logic in endpoints.

I don't currently have a good substitute, but I do suggest we try to find a more precise term.

2021-04-21 05:39 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +As established above, an important aspect when modelling data in Sesam is the use of globals. Albeit before reaching the global stage and after completion of the global stage, when modelling your dat
The first is the case. Therefore I chose modelling.

;- can be used to denote a pause, that is almost as long as a . 
I haven't got too strong opinions on this one, so I can change it.

2021-04-21 07:34 UTC, ga-hegsvold requested changes
Other than a small "typo" I think this is coming together nicely.

2021-04-21 07:34 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +If we start shaping and customizing data too soon in the flow, it's much harder, if not impossible, to reuse the data for different purposes later. A rule of thumb is therefore to minimize the amount
Use lower case "if" here: "Therefore, If we" -> "Therefore, if we"

2021-04-21 07:46 UTC, ga-hegsvold approved these changes

2021-04-21 11:33 UTC, gabriellsesam approved these changes

2021-05-05 07:28 UTC, merged