#251 : Adding - Filter entities on the way out
datanav/docs pull request #257
Opened 2021-04-20 13:06 UTC by JonasAls89

2021-04-21 06:38 UTC, gabriellsesam commented on training/010_architecture_and_concepts/030_Novice.rst
> +Imagine you are working on a large dataset produced by a global pipe. You quickly recognize that the amount of data and all its properties is not that relevant to you. Therefore, one of the first thi
´namelig` typo -> ´namely´

You should explicitly say that if the entity is not of type Employee it is therefore not relevant and can be filtered out. I think the "NotRelevant" property is confusing here because there is no mention of property's value.
```
if the entity is of type: "Employee" - add properties "Salary", "Position" and "Goals", albeit if it is not of type "Employee" add the property "NotRelevant". This written logic will provide us with a second means of filtering, namelig the property "NotRelevant".
```

2021-04-21 06:39 UTC, gabriellsesam commented on training/010_architecture_and_concepts/030_Novice.rst
> +Filtering entities after the global stage of modelling is a common use case. Filtering gives the ability to work with subsections of a dataset. It is therefore often times used when working on large
`It is therefore often times used` -> `It is often used`

2021-04-21 06:40 UTC, gabriellsesam commented on training/010_architecture_and_concepts/030_Novice.rst
> +Filtering entities after the global stage of modelling is a common use case. Filtering gives the ability to work with subsections of a dataset. It is therefore often times used when working on large
`filtering is often times used` -> `filtering is often used`

2021-04-21 06:40 UTC, gabriellsesam commented on training/010_architecture_and_concepts/030_Novice.rst
> +Filtering entities after the global stage of modelling is a common use case. Filtering gives the ability to work with subsections of a dataset. It is therefore often times used when working on large
`*_deleted* entities never leave Sesam` -> `*_deleted* entities rarely leave Sesam`

2021-04-21 06:41 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +Filtering entities after the global stage of modelling is a common use case. Filtering gives the ability to work with subsections of a dataset. It is therefore often times used when working on large
subsections -> subsets

2021-04-21 06:45 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +Filtering entities after the global stage of modelling is a common use case. Filtering gives the ability to work with subsections of a dataset. It is therefore often times used when working on large
I don't agree. _deleted entities quite often leave Sesam and we often want them to. Maybe we don't have to explain the practical differance between _filetered and _deleted here, but since _deleted entities always are sent out of Sesam unless otherwise stated, I think this should come out in the text

2021-04-21 06:49 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +Filtering entities after the global stage of modelling is a common use case. Filtering gives the ability to work with subsections of a dataset. It is therefore often times used when working on large
Good point that they are processed downstream yea. Albeit, when an _id is first introduced in Sesam, I don't think it ever leaves again, regardless of state of _deleted. I think Product talked about introducing a feature where you can set a time-limit within which entities exist as _deleted, but not sure it has been implemented yet.

2021-04-21 06:51 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +Filtering entities after the global stage of modelling is a common use case. Filtering gives the ability to work with subsections of a dataset. It is therefore often times used when working on large
subsection: a division of a section.

subset: a part of a larger group of related things.

I think they are synonyms, so I assume we can use either one?

2021-04-21 06:53 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +Filtering entities after the global stage of modelling is a common use case. Filtering gives the ability to work with subsections of a dataset. It is therefore often times used when working on large
Well, then we should specify that _deleted entities can (and often are) sent out of Sesam, but they might not be "removed" from the datasets unless you yourself remove the dataset.

2021-04-21 07:10 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +Imagine you are working on a large dataset produced by a global pipe. You quickly recognize that the amount of data and all its properties is not that relevant to you. Therefore, one of the first thi
"Albeit, since the state of the data does not immediately satisfy your needs, you decide to add specific properties given a specific condition; i.e., if the entity is of type: "Employee" - add properties "Salary", "Position" and "Goals", albeit if it is not of type "Employee" apply a filter to exclude that entity."
Long sentence with two "albeit". Also, I'm not sure I follow the logic in the sentence. "since the state of the data does not..." -> this part was not intuitive for me

2021-04-21 07:13 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +Imagine you are working on a large dataset produced by a global pipe. You quickly recognize that the amount of data and all its properties is not that relevant to you. Therefore, one of the first thi
noted. What word would you go with instead of "state"? or suggestion on rephrasing the first sentence?

2021-04-21 07:15 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +Imagine you are working on a large dataset produced by a global pipe. You quickly recognize that the amount of data and all its properties is not that relevant to you. Therefore, one of the first thi
So far, looks like this: Albeit, since the state of the data does not immediately satisfy your needs, you decide to add specific properties given a specific condition; i.e., if the entity is of type: "Employee" - add properties "Salary", "Position" and "Goals". Finally, if it is not of type "Employee" apply a filter to exclude that entity.

2021-04-21 07:29 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +Imagine you are working on a large dataset produced by a global pipe. You quickly recognize that the amount of data and all its properties is not that relevant to you. Therefore, one of the first thi
Could we split these filter situations into two more clearly separate situations? The first one applies to the correct data coming into the pipe, the second applies to the quality of the data coming out of the pipe. Right now they are kinda mushed together

2021-04-21 07:30 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +Imagine you are working on a large dataset produced by a global pipe. You quickly recognize that the amount of data and all its properties is not that relevant to you. Therefore, one of the first thi
alrigth

2021-04-21 08:13 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +Filtering entities after the global stage of modelling is a common use case. Filtering gives the ability to work with subsections of a dataset. It is therefore often times used when working on large
Regarding sections and sets: Considering we have "data**sets**" in Sesam, I think it's more precise to use "subset" than "subsection".
As a side note: for the dataset source there is a property called "subset" that only reads entities specified in the "subset" from the source.

2021-04-21 08:17 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +Filtering entities after the global stage of modelling is a common use case. Filtering gives the ability to work with subsections of a dataset. It is therefore often times used when working on large
Think that is a valid argument. Correcting it.

2021-04-21 08:30 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +Imagine you are working on a large dataset produced by a global pipe. You quickly recognize that the amount of data and all its properties is not that relevant to you. Therefore, one of the first thi
> noted. What word would you go with instead of "state"? or suggestion on rephrasing the first sentence?

Maybe "content"? Or maybe just skip it: "since the data does not immediately satisfy your needs"

2021-04-21 08:35 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +Imagine you are working on a large dataset produced by a global pipe. You quickly recognize that the amount of data and all its properties is not that relevant to you. Therefore, one of the first thi
Personally I do appreciate "state". It denotes the fact that we are shaping the data in our DTL and aligns well with the fact that data flows in states through pipes.

2021-04-21 09:19 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +Imagine you are working on a large dataset produced by a global pipe. You quickly recognize that the amount of data and all its properties is not that relevant to you. Therefore, one of the first thi
I don't really have a strong opinion either way regarding "state". Just wanted to offer a couple of alternatives.
And to be clear: by "state of the data", I assume you mean which properties are currently present on the entities, right?

2021-04-21 09:26 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +Imagine you are working on a large dataset produced by a global pipe. You quickly recognize that the amount of data and all its properties is not that relevant to you. Therefore, one of the first thi
That is right, yea.

2021-04-21 11:32 UTC, gabriellsesam approved these changes

2021-04-21 14:48 UTC, ga-hegsvold requested changes

2021-04-21 14:48 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +Filtering entities after the global stage of modelling is a common use case. Filtering gives the ability to work with subsets of a dataset. It is therefore often used when working on large datasets w
Is it sensible to use *_deleted* to reference entities with _deleted: true? Is this explained somewhere?
I don't mind us using it as long as it's explicitly explained prior to its usage.

2021-05-10 09:16 UTC, ga-hegsvold requested changes

2021-05-10 09:16 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +Imagine you are working on a large dataset produced by a global pipe. You quickly recognize that the amount of data and all its properties is not that relevant to you. Therefore, one of the first thi
Bare in mind I might be missing some context here, but reading only the "Filter entities on the way out" section, this example confuses me a bit.
Is there an example somewhere nearby of the data that is referred to in this paragraph?
Phrases like "You quickly recognize..." and "As you look closely..." would imply I'm actually looking at an example while reading this, no?

The order in which filters are step-wise added can of course vary, but I think it's sensible to point out that it's usually a good idea to start by filtering in relevant entities based on rdf:type(s).
Then you usually add any missing properties required by the target system by hopping to related datasets.
And lastly you can/should remove irrelevant properties.
During these steps you might also find that additional filters are required to further narrow down entities to those expected by the target system.

Thou, I would call adding and removing properties for "shaping" or "transforming", and not "filtering", so not sure if that is relevant to mention in this section.

2021-05-12 06:16 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +Imagine you are working on a large dataset produced by a global pipe. You quickly recognize that the amount of data and all its properties is not that relevant to you. Therefore, one of the first thi
I feel like the above comment is a bit hard to address...

The example given is in theory, as this is in the architecture section of the book, I think it is proper to minimise the amount of DTL we use, as that should be used in the DTL section. Additionally, the phrasing used is in alignment with what we agreed upon, i.e. you are ... you should ... etc. Finally, the section starts off with "imagine you are working... " this implies that the coming example is in theory.

Again rdf:type, I believe, should be in the DTL section. If I introduce rdf:type now, I need to explain the concept first and then how we use rdf:type in Sesam DTL as well. I think this broadens the scope of this section too much.

I think your last comment, albeit I agree semantically, is more of a philosophical question. I don't think we should make it harder for the reader to consume. Therefore I think it is proper to not introduce words like shaping and transforming on top of filtering. This is for Novice, so I do think we should not assume too much about their knowledge..

Counter feedback?

2021-05-12 07:24 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +Filtering entities after the global stage of modelling is a common use case. Filtering gives the ability to work with subsets of a dataset. It is therefore often used when working on large datasets w
corrected. 👍

2021-05-12 08:30 UTC, ga-hegsvold approved these changes

2021-05-12 08:30 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +Imagine you are working on a large dataset produced by a global pipe. You quickly recognize that the amount of data and all its properties is not that relevant to you. Therefore, one of the first thi
@JonasAls89 
I see how this example can be tricky to write given it's in an early chapter.

My initial reaction was mainly about the phrasing, that it felt a bit.. strong (not sure if that word best describes it) for it to be a theoretical/hypothetical example. When I read "You quickly recognize..." my brain went "Do I? I don't see any data...". Since it's an imaginary example it might be phrased something like "Let's say you recognize..." or "Assume you recognize..." just to reinforce to the reader that this is indeed a hypothetical example.

I agree that undefined terms and concepts should not be written about here.

The point of this example, as I understand it, is to show that it's ok to use multiple filters, and I think that point is conveyed to the reader.

2021-05-12 08:34 UTC, merged