199
datanav/docs pull request #262
Opened 2021-04-27 08:09 UTC by erik-leven

2021-04-27 13:14 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
>  located one, or a set of pipes, in a subscription with many pipes.
located -> locate

2021-04-27 13:15 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Upon entering a pipe you will by default be sent to the pipe’s “Graph”
Won't you be placed in the tab you last accessed?

2021-04-27 13:44 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Upon entering a pipe you will by default be sent to the pipe’s “Graph”
haha, you're right. Never remarked on that before 🗡️

2021-05-12 12:28 UTC, ga-hegsvold requested changes

2021-05-12 12:28 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +please look `here <management-studio.html#section>`__.
Link is broken. I find links to be a bit tricky in RST.

I suggest we use the section title we reference as the name of the link, and not just "here":
"...please see \`Sesam Management Studio <../../management-studio.html>\`_."

Or perhaps better, add an anchor in the Sesam Management Studio section:
```
.. _sesam-management-studio:

=======================
Sesam Management Studio
=======================

```
and refere to it by using `:ref:`:
"...please see :ref:\`sesam-management-studio\`."

Using `:ref:` automatically figures out relative file location and gives us the referred section title in the link. Makes it a lot easier to understand the context.

2021-05-12 12:28 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +When logging in to the portal you will be met with a page like the figure below
Punctuation or maybe a colon after this sentence?

2021-05-12 12:28 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +list, as seen in the figure below, diplays all the available pipes in your subscription as well as
"as seen ... below" is used twice in a row. The latter feels redundant.
I think "Unless filters are applied, this list diplays..." is sufficient.

Oh, and a small typo: "fiters" -> "filters"

2021-05-12 12:28 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
>  located one, or a set of pipes, in a subscription with many pipes.
Suggested rewording: "one, or a set of pipes" -> "one, or a subset of pipes"

2021-05-12 12:28 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
>  maybe?]). For now, we will focus on four of the pipe’s subpages: Config,
Do we officially call these "subpages" or "tabs" or something else?
I've just called them "tabs" so far.

2021-05-12 12:28 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +The systems tab looks very much like the pipe tab in the Pipe overview above.
I think we should refer to the left-menu items as something other than "tabs" to avoid potential confusion if we also call the Config, Graph, Overview, etc for "tabs".
Maybe "menu item"?

2021-05-12 13:00 UTC, ga-hegsvold commented
I took the liberty of updating the cross reference to the Sesam Management Studio chapter.

2021-05-12 15:01 UTC, gabriellsesam commented
Training branch needs to be merged into this

2021-05-12 15:42 UTC, ga-hegsvold commented
Merged training branch into 199. Hope I picked the correct parts of the conflicting changes 🤞🏻

2021-05-24 13:50 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +When logging in to the portal you will be met with a page like the figure below
fixed

2021-05-24 13:51 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +list, as seen in the figure below, diplays all the available pipes in your subscription as well as
agreed

2021-05-24 13:52 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
>  located one, or a set of pipes, in a subscription with many pipes.
agreed

2021-05-24 13:53 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
>  maybe?]). For now, we will focus on four of the pipe’s subpages: Config,
Hmm, I suppose both work equally. Tabs it is

2021-05-24 13:54 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +The systems tab looks very much like the pipe tab in the Pipe overview above.
I guess we can get a consensus on next meeting for this

2021-05-25 08:23 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
> +The systems tab looks very much like the pipe tab in the Pipe overview above.
consensus:
When reffering to an item in the left hand list of the portal, use the wording:
```
The left-menu item "Systems"
```
When you have clicked on Systems, you can refer to the page as the
```
Systems View
```

2021-05-27 06:21 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +please look `here <management-studio.html#section>`__.
fixed

2021-06-04 11:34 UTC, ga-hegsvold requested changes
@erik-leven Did you push your updates? I don't see them here yet...

2021-06-04 11:34 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +When logging in to the portal you will be met with a page like the figure below
I don't see a punctuation or colon yet..? Have you pushed your updates to the remote branch?

2021-06-04 11:34 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +list, as seen in the figure below, diplays all the available pipes in your subscription as well as
I don't see any upates here either.

2021-06-16 06:30 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +When logging in to the portal you will be met with a page like the figure below
This is weird. I have a colon in the .rst file, but it wont show in the html-version or in the diff version here...

2021-06-16 08:25 UTC, ga-hegsvold requested changes
Almost there. Noticed a few details that should be corrected. See comments.

2021-06-16 08:25 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
>  .. figure:: ./media/Architecture_Beginner_The_Sesam_Portal_B.png
Please remove "figure 1.1.6B" and replace with for instance "the figure below".

2021-06-16 08:25 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
>     about in section [link]. One
"One" looks very lonely. Maybe find it some company or remove it. ;-)

2021-06-16 08:25 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
>     some occasions where there is no output so be seen but for now you
> no output so be seen

-->

> no output to be seen

2021-06-16 08:25 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
>     can assume that there will always be an output to be see for each
> to be see

-->

> to be seen

2021-06-16 08:25 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
>     much time the processing took and much more. If a pipe is not be able
> If a pipe is not be able

-->

> If a pipe is not able

2021-06-16 08:25 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +The systems manu looks very much like the pipe tab in the Pipe overview above.
typo: "manu" --> "menu" or maybe call it "page" to be consistent with the Pipe section above.

"pipe tab" --> "pipe page" ?

2021-06-16 08:25 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
>     systems and many of have very different configuration. There are
> many of have

-->

> many of them have

2021-06-16 08:25 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
>     of environmental variables used by the Microservice.
"environmental" --> "environment"

2021-06-16 08:25 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +>>>>>>> 90529b39dfb96e13941f5cbee9f3dbf108993705
Looks like leftovers from a merge conflict.

2021-08-18 12:30 UTC, gabriellsesam approved these changes

2021-08-18 13:28 UTC, ga-hegsvold approved these changes
Nice!

2021-08-18 14:00 UTC, ga-hegsvold commented
I'll start working on resolving the conflicts for this PR.

2021-08-18 14:12 UTC, ga-hegsvold commented
I've kept most of the latest changes, but replaced "height" and "width" params using absolute pixel values for figures to only use "width": 100%. I think that should be sufficient formatting.
If not we can tweak it later.

2021-08-18 14:16 UTC, merged