#240: Architecture Beginner: Globals as a Concept
datanav/docs pull request #265
Opened 2021-04-28 06:07 UTC by gabriellsesam

2021-05-07 09:48 UTC, JonasAls89 reviewed
test

2021-05-07 11:14 UTC, JonasAls89 reviewed
Bra avsnitt, men lidt feedback da.

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
>  These are the fundamental parts which make up a Sesam integration pipeline:
dataflow instead of integration pipeline

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
>     beginning and end of the pipeline flows and are often referred to as
dataflow

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
>     dataset depending on where the pipe is located inside the integration
dataflow

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
>     to i.e., a table in an SQL database. Datasets are where the pipes store the
a SQL database. "an" does not always apply to abbreviations.

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
>     functionalities later in this book (maybe a link?).
maybe a link? Is that supposed to be there?...

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
>     Sesam can be compared to individual rows in an SQL table and can
a SQL table

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +data which represents the same concept in the real world but normally is stored separately in
respresent. Not represents in this case.

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +in the binary world.
double "in"??

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +know which concept or type of entity an endpoint wishes to receive, you can quickly pick
outbound

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Globals are the aggregation of objects about the same concepts.
shouldn't it strictly be "the same concept" globals is only about one concept.

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +from a shipping and a sales system respectively. The datasets produced by these pipes both
shipping system and a sales system...

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +goods, while the sales systems cares about what goods the customer usually shops for and analytics
while the sales system ...

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +We now have a aggregated view of the customers which join together, giving us both
an aggregated view ...

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +A golden records consists of the properties which together represent the most
A golden record ...

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +property "address", but the shipping systems version of this address is always most up to date.
but the version of the address, received from the shipping system, is always most up to date.

2021-05-07 11:14 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +by our shipiing system, which we can thereafter use in any downstream pipes
shipping

2021-05-12 10:48 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
>  These are the fundamental parts which make up a Sesam integration pipeline:
We need to fix in another PR which is about this section

2021-05-12 10:48 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
>     beginning and end of the pipeline flows and are often referred to as
We need to fix in another PR which is about this section

2021-05-12 10:48 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
>     dataset depending on where the pipe is located inside the integration
We need to fix in another PR which is about this section

2021-05-12 10:48 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
>     to i.e., a table in an SQL database. Datasets are where the pipes store the
We need to fix in another PR which is about this section

2021-05-12 10:48 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
>     Sesam can be compared to individual rows in an SQL table and can
We need to fix in another PR which is about this section

2021-05-12 10:48 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
>     functionalities later in this book (maybe a link?).
We need to fix in another PR which is about this section

2021-05-12 13:25 UTC, ga-hegsvold requested changes
I think this is overall very well written. Just a couple of comments.

2021-05-12 13:25 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +then you can easily use the "rdf:type" to narrow down which entities you want.
Is "rdf:type" defined prior to this section?
If not we might get away with forward referencing the section where it will be defined.

2021-05-12 13:25 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +This means that we can define a golden attribute "golden-address" with the address provided
Do we actually use the "golden-" prefix for these golden properties or is this more of an illustration?
From my experience, the golden properties are defined in the global pipes and therefore get the corresponding global namespace.
So in this example we could add a property "address" in "global-customer" which would give us the output "global-customer:address" as the "golden" property.

2021-05-12 13:52 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
> +This means that we can define a golden attribute "golden-address" with the address provided
agree, I should change this

2021-06-03 10:29 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
> +then you can easily use the "rdf:type" to narrow down which entities you want.
RDF:Type is in the "special sesam attribtues" topic which comes right after this one. Adding a reference :)

2021-06-11 08:48 UTC, gabriellsesam commented
I would like feedback on how i set the Related topics. I added the chapter and difficulty level because there were so many - but it's up for changing based on what you guys think.

2021-06-15 14:05 UTC, ga-hegsvold requested changes
Lots of good stuff here! I think the examples you use to drive home the points are very good.
There are some details I'd like to bring attention to (as usual ;-) ). See my comments.

2021-06-15 14:12 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  DTL Intermediate: :ref:`source-subset-3-3`
I like what you did here by adding section prefixes to the references. Not 100% sold on the "Next topic" part, but otherwise big thumbs up!

2021-06-16 07:19 UTC, JonasAls89 approved these changes
Well written!

I think GAH had some good viewpoints here and especially on keeping with join/merge/mix etc.

I'll approve for now, seeing that you will sort out the comments from GAH.

2021-06-16 07:19 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +A global is the aggregation of objects categorized as the same concept.
agreed

2021-08-18 14:26 UTC, ga-hegsvold commented
Fixed merge conflict.

2021-09-08 13:51 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
> +global-customer without needing to worry about the original origin of the attribute.
Hmm I like it as a pretense for the next time you touch on globals, but I understand it may be a bit far outside of what the reader has learned so far.

2021-09-24 11:52 UTC, ga-hegsvold submitted a review, later dismissed

2021-09-24 11:52 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +global-customer without needing to worry about the original origin of the attribute.
We actually have a separate section for Golden records (https://docs.sesam.io/data-modelling.html#golden-record).
It might need some clarifications, but at least it's there.
Can you add a link to it under `seealso`?

2021-11-10 12:20 UTC, gabriellsesam commented
Also merged "master" into this branch for good measure

2021-11-10 12:20 UTC, merged