#241 : Adding Special Sesam Attributes section
datanav/docs pull request #266
Opened 2021-04-29 08:05 UTC by JonasAls89

2021-04-29 08:55 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Properties can also have namespaces, but here the ~: part is not used. global-person:fullname is an example of such a namespaced property. Namespaced properties are essential when merging to avoid na
and to maintain provenance of the properties -> and to maintain the source of properties ?

2021-04-29 08:56 UTC, gabriellsesam commented on training/010_architecture_and_concepts/020_Beginner.rst
> +The RDF type is metadata used to relate data and give some semantic context. When used with a namespace, it keeps track of the origin of the data, as well as the business type. It is composed upon in
Should give an example or reference "¨~:foo:bar" above

2021-05-05 08:12 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +The RDF type is metadata used to relate data and give some semantic context. When used with a namespace, it keeps track of the origin of the data, as well as the business type. It is composed upon in
added this

2021-05-05 08:12 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Properties can also have namespaces, but here the ~: part is not used. global-person:fullname is an example of such a namespaced property. Namespaced properties are essential when merging to avoid na
changed as almost suggested

2021-05-07 09:27 UTC, gabriellsesam approved these changes

2021-05-12 15:20 UTC, ga-hegsvold requested changes

2021-05-12 15:20 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Properties can also have namespaces, but here the ~: part is not used. global-person:fullname is an example of such a namespaced property. Namespaced properties are essential when merging to avoid na
I think we need to clarify namespaces and namespaced identifiers a bit. This topic can be a bit tricky to grasp.

I'll give it a shot:

Namespaces in Sesam are primarily used on properties, and its main functions are to ensure uniqueness across sources and to maintain property provenance (as you explain).
`"global-person:fullname"` is an example of a namespaced property, where "global-person" is the namespace and "fullname" is the property name (or key?).

Namespaced identifiers (NIs) are identifiers (i.e. property values) given a namespace.
`"source:reference": "~:foo:bar"` is an example of a NI, where "source" is the property namespace, "reference" is the property name (key?), "foo" is the namespace of the references data and "bar" is the identifier (property value) matching an identifier in the referenced data. (maybe use an example that illustrates how a NI matches an identifier/$ids in another dataset?)
The "\~" is Sesam's way of telling you that it is of datatype NI. (this sentence should probably be improved)

NIs in Sesam are similar to foreign keys in databases in that NIs are a visual indication of how data is connected, and enables easier and more precise joins. However, Sesam does not enforce any relationship between NIs and the referenced properties.

2021-05-18 08:24 UTC, ga-hegsvold requested changes

2021-05-18 08:24 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Namespaces are inspired by RDF (The Resource Description Framework). You'll see them in terms of namespaced identifiers - also called NIs. A NI is a special datatype defined in the entity data model.
> Namespaces are inspired by RDF (The Resource Description Framework)

It may be true that the use of namespaces in Sesam was inspired by RDF, but the concept of namespaces have existed for many years and are used in many different places (Linux kernel, programming languages, XML, etc.).

Maybe we should add that "Namespaces *in Sesam* are inspired by RDF" if we need to reference RDF at all?

I think this paragraph overlaps, at least in part, with the NI explanation below.
I also think it would be easier for the reader to be introduced to the most common use of namepaces first (as property prefix), before diving into NIs.

2021-05-18 08:34 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Namespaces are inspired by RDF (The Resource Description Framework). You'll see them in terms of namespaced identifiers - also called NIs. A NI is a special datatype defined in the entity data model.
so maybe just cut this paragraph out @ga-hegsvold ?

2021-05-18 08:41 UTC, ga-hegsvold requested changes

2021-05-18 08:41 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Namespaces are inspired by RDF (The Resource Description Framework). You'll see them in terms of namespaced identifiers - also called NIs. A NI is a special datatype defined in the entity data model.
Yeah, I think the remaining paragraphs cover namespaces and NIs sufficiently for beginner level.
And maybe cut "Properties can also have namespaces, but here the ~: part is not used." considering "~" will be explained further down.

2021-05-18 08:44 UTC, ga-hegsvold approved these changes

2021-05-18 08:46 UTC, merged