#243 : Adding NI for foreignKeys and make-ni examples
datanav/docs pull request #267
Opened 2021-04-29 11:10 UTC by JonasAls89

2021-04-29 11:24 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +In the below example, ["make-ni"] will be used. A NI in Sesam works like a foreign key in a relational database. As such, it shows the relation between data objects and enables the joining of these.
Should we say why we need them? I mean, what we're doing here is basically just renaming a variable. Should we show an example of how we can actually use ne NI's in an equality, and maybe compare it to without a NI?

2021-04-29 11:25 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +As can be seen in the above dataset, the property with the key: "mssql-accounts:phone-ni" is the result of the function ["make-ni"] as defined in the above pipe config. The value can be used to join
uten : etter key?

2021-05-05 11:00 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +In the below example, ["make-ni"] will be used. A NI in Sesam works like a foreign key in a relational database. As such, it shows the relation between data objects and enables the joining of these.
I think what you are suggesting in this comment, will be covered in other sections of this page. When we get a more complete picture, then maybe we need to revise some of it, but I think for now, I'll let it stay.

2021-05-05 11:01 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +As can be seen in the above dataset, the property with the key: "mssql-accounts:phone-ni" is the result of the function ["make-ni"] as defined in the above pipe config. The value can be used to join
Endring implementeres

2021-05-07 09:04 UTC, gabriellsesam approved these changes

2021-05-14 08:28 UTC, ga-hegsvold requested changes

2021-05-14 08:28 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +Continuing along the lines of joining data, namespaced identifiers (NI's) come into play. NI's are used in Sesam to create unique identifiers inside one Sesam datahub. In order to create them, you ca
typo: "NI's" -> "NIs"

> NI's are used in Sesam to create unique identifiers inside one Sesam datahub.

NIs are not really unique identifiers in Sesam, but are typically used to reference an identifier or a NI in a related dataset.

2021-05-18 07:45 UTC, ga-hegsvold approved these changes

2021-05-18 07:45 UTC, merged