#244 : Adding Full Outer Join
datanav/docs pull request #270
Opened 2021-05-05 14:34 UTC by JonasAls89

2021-05-07 09:06 UTC, gabriellsesam requested changes
Veldig bra, fant bare en skrivefeil

2021-05-07 09:06 UTC, gabriellsesam commented on training/010_architecture_and_concepts/030_Novice.rst
> +A note on the handling of null values. In Sesam null values is not existing. Meaning, as opposed to a full outer join which will populate empty entries in the join between tables with null values, th
In Sesam null values **are** not existing

2021-05-07 09:15 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +A note on the handling of null values. In Sesam null values is not existing. Meaning, as opposed to a full outer join which will populate empty entries in the join between tables with null values, th
corrected

2021-05-07 09:19 UTC, gabriellsesam approved these changes

2021-05-12 10:52 UTC, mofsesam approved these changes

2021-05-12 10:52 UTC, mofsesam commented on training/010_architecture_and_concepts/030_Novice.rst
> +.. figure:: ./media/Full_Outer_Join.png
Maybe figures from existing course could illustrate this better than a venn diagram? Showing example tables and how the merge.

2021-05-12 10:54 UTC, merged