#252 : Adding Copy Novice
datanav/docs pull request #277
Opened 2021-05-12 12:07 UTC by JonasAls89

2021-05-12 12:26 UTC, gabriellsesam requested changes
Very good example and good explanation, but I think it we can be more clear in some of the sentences.

I'd also love to see a sentence or two about copying all keys from a given namespace, like
`["copy", "golden-object:*"]`

2021-05-12 12:26 UTC, gabriellsesam commented on training/030_dtl/030_Novice.rst
> +Copy is one of the most fundamental DTL functions you will be using in Sesam when transforming your data. Copy might also be the most frequently used DTL function. The main reason for this is that it
`allows you to copy data by`
I suggest we should specify that we copy from the source to the target

2021-05-12 12:26 UTC, gabriellsesam commented on training/030_dtl/030_Novice.rst
> +The first argument in the above declaration accepts all values by the use of asterisk, whilst the second argument with the "_" prefix before the asterisk blacklists all values that has an "_" as part
`The first argument in the above declaration accepts all values by the use of asterisk`
->
`The first argument in the above declaration copies everything from your source to your output by the use of asterisk`

2021-05-12 12:26 UTC, gabriellsesam commented on training/030_dtl/030_Novice.rst
> +The first argument in the above declaration accepts all values by the use of asterisk, whilst the second argument with the "_" prefix before the asterisk blacklists all values that has an "_" as part
`blacklists all values that has an "_" as part of their key property`
->
`blacklists all values whose keys start with "_"`

2021-05-12 12:26 UTC, gabriellsesam commented on training/030_dtl/030_Novice.rst
> +Data entering a pipe from the system "sesam-training":
Suggest to use the pipe name from the example, like:
`Data entering the pipe mssql-accounts`

2021-05-12 12:26 UTC, gabriellsesam commented on training/030_dtl/030_Novice.rst
> +As can be seen from the above produced data, the property with the key "_position" has been filtered by the ``["copy"]`` function and its arguments.
maybe this is just subjective but
`from the above produced data`
->
`from the produced data above`

2021-05-12 12:26 UTC, gabriellsesam commented on training/030_dtl/030_Novice.rst
> +As can be seen from the above produced data, the property with the key "_position" has been filtered by the ``["copy"]`` function and its arguments.
`filtered by the ``["copy"]`` function and its arguments.`
->

filtered by the blacklist parameter `"_*"` in the ``["copy"]`` function.

2021-05-12 12:46 UTC, JonasAls89 commented on training/030_dtl/030_Novice.rst
> +As can be seen from the above produced data, the property with the key "_position" has been filtered by the ``["copy"]`` function and its arguments.
Implemented everything aside from this comment.

2021-05-12 12:49 UTC, gabriellsesam approved these changes

2021-05-14 08:34 UTC, ga-hegsvold approved these changes

2021-05-18 06:42 UTC, merged