#234: Merge 234 to training
datanav/docs pull request #282
Opened 2021-05-18 13:45 UTC by ga-hegsvold

Architecture & Concepts: Beginner - Datasets

2021-05-19 05:57 UTC, JonasAls89 requested changes

2021-05-19 05:57 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +data record, called *entity*, consisting og key-value pairs.
typo "og" -< of.

2021-05-19 05:57 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +A dataset with two people entities could look something like this:
I would rephrase this, "people entities" comes across as a specific type of entity, i.e.: A dataset with two entities concerning persons could look like this:

2021-05-19 14:27 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +data record, called *entity*, consisting og key-value pairs.
fixed

2021-05-19 14:27 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +A dataset with two people entities could look something like this:
fixed

2021-05-19 14:29 UTC, JonasAls89 approved these changes

2021-05-21 13:11 UTC, gabriellsesam approved these changes

2021-05-21 13:11 UTC, merged