#249 : Adding corrections
datanav/docs pull request #288
Opened 2021-05-21 11:51 UTC by JonasAls89

2021-05-21 12:51 UTC, ga-hegsvold requested changes
Overall I think this is good, but see my comments and questions.

2021-05-21 12:51 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +	  "mssql-accounts:hobbies": "Builds LEGO"
We should avoid using database type ("mssql" in this case) as the system-part of the namespace in our examples.
Use the (fictional) name of the system instead.
Also use singular form for the table/datatype part of the namespace.
This is in accordance with our Best Practices.

So instead of "mssql-accounts", use for instance "crm-account" or whatever system name is appropriate for this example.

2021-05-21 12:51 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +After comparing the current shape of your data to the target system schema, you realize only the properties "position", "id" and "phone" are needed. In addition, you recognize that the first letter o
This might be the OCD part of me talking, but I think it's a bit more pleasant to read if the properties that are referred to in the paragraph have the same order as they have in the example above:
"the properties "position", "id" and "phone" are needed" -> "the properties "id", "phone" and "position" are needed"

2021-05-21 12:51 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +As an example, the data presented below is produced by the global pipe named "global-person":
This sentence could be simplified to:
As an example, the data presented below is produced by the pipe "global-person":

2021-05-21 12:51 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +An outbound dataflow consists of the pipe which reads from a global pipe, the outbound pipe which sends data to an external system and all the pipes in between. In these outbound dataflows it is typi
Could this sentence:
> An outbound dataflow consists of the pipe which reads from a global pipe, the outbound pipe which sends data to an external system and all the pipes in between.

be simplified to:

> An _outbound_ dataflow consists of all pipes downstream from a global pipe.

maybe with emphasis on the term "outbound"?

2021-05-21 13:25 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +After comparing the current shape of your data to the target system schema, you realize only the properties "position", "id" and "phone" are needed. In addition, you recognize that the first letter o
as I've also got a little OCD I appreciate the logic in that. ;) will implement.

2021-05-21 14:33 UTC, ga-hegsvold requested changes
I didn't notice on the first read, but I see that some of the function references are a bit difficult to read. I think we should prettify and make them stand out a bit more. See suggestions.

2021-05-25 07:51 UTC, ga-hegsvold requested changes
The new formatting looks good. Just one tiny detail. See below.

2021-05-25 07:51 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +	["rename", "id", "Id"]
Would you mind listing these in alphabetical order as well (id, phone, position)? -OCD

2021-05-25 07:59 UTC, ga-hegsvold approved these changes

2021-06-12 05:41 UTC, gabriellsesam approved these changes

2021-06-15 13:27 UTC, merged