#246: merge 246 with training
datanav/docs pull request #289
Opened 2021-05-24 07:53 UTC by erik-leven

2021-05-27 15:00 UTC, ga-hegsvold requested changes
Haven't managed to read through everything yet, but I wanted to give some preliminary feedback.

2021-05-28 09:09 UTC, ga-hegsvold requested changes
I think the content here is very good. Just noticed a few typos here and there, and added a couple of suggestions.

2021-05-28 09:09 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +The dataset hr-person does not contain any data regarding "hours-pr-project" or "weekly-hours-billed" and can therefore be left out of the prioritations.
"prioritations" -> "prioritizations" ?

2021-05-28 09:09 UTC, ga-hegsvold commented on training/030_dtl/020_Beginner.rst
Missing code block here. Have you pulled all changes from the training branch?

2021-05-28 09:09 UTC, ga-hegsvold commented on training/030_dtl/020_Beginner.rst
Missing code block here as well.

2021-06-16 06:32 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Since they are a relatively common way to store data, Sesam has a ready built-in connector for MSSQL databases. The MSSQL system inside Sesam connects to an MSSQL database by sending the host, databa
agreed and fixed

2021-06-16 06:34 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +Global datasets lies at the heart of a well managed Sesam architecture. They are created by global pipes and often consist of aggregated data from several different sources enabling a higher level of
fixed

2021-06-16 06:34 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +Creating global datasets allows a Sesam installation to:
fixed

2021-06-16 06:36 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +		A semantic grouping of the data makes the data it self easier to understand and more intuitive to work with, both in turns of excisting architecture and new projects. For excisting architecture, se
fixed

2021-06-16 06:36 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +		One effect of global datasets is the ability to perform active master data management through setting golden records. Golden records are where Sesam architectures may localize and prioritize their
fixed

2021-06-16 06:37 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +		Golden records are created with the "coalesce" function, as shown in the example below.
yeah I agree, looks much better

2021-06-16 06:38 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +	A global pipe, "global-person", has three source datasets, crm-person, hr-person and economy-person. The crm-person dataset has high quality work experience data and medium quality hours logged data
maybe decide on Friday?

2021-06-16 06:39 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +In this case, all three source datasets has an email property. If the email in hr-person is not null, that email will be the value in our global property. Should it have a null value the email from c
agreed

2021-06-16 06:39 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +The dataset hr-person does not contain any data regarding "hours-pr-project" or "weekly-hours-billed" and can therefore be left out of the prioritations.
fixed

2021-06-16 06:41 UTC, erik-leven commented on training/030_dtl/020_Beginner.rst
pulled now

2021-06-16 06:42 UTC, erik-leven commented on training/030_dtl/020_Beginner.rst
pulled now

2021-06-16 08:46 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Since they are a relatively common way to store data, Sesam has a ready built-in connector for MSSQL databases. The MSSQL system inside Sesam connects to an MSSQL database by sending the host, databa
Could you also add two single quotes around system:mssql since it's a Sesam config thing: \``system:mssql``

2021-06-16 08:46 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +		A semantic grouping of the data makes the data it self easier to understand and more intuitive to work with, both in turns of excisting architecture and new projects. For excisting architecture, se
Think you missed this one:
"architecture" -> "architectures" or "the existing architecture"

2021-06-16 08:57 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +The dataset hr-person does not contain any data regarding "hours-pr-project" or "weekly-hours-billed" and can therefore be left out of the prioritations.
Did you push this fix? It still says "prioritations" on my end.

2021-06-16 09:01 UTC, ga-hegsvold requested changes
Most fixes are good, but some are missing (at least on my end). See comments.

2021-06-29 06:57 UTC, erik-leven commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Since they are a relatively common way to store data, Sesam has a ready built-in connector for MSSQL databases. The MSSQL system inside Sesam connects to an MSSQL database by sending the host, databa
Fixed

2021-06-29 06:57 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +		A semantic grouping of the data makes the data it self easier to understand and more intuitive to work with, both in turns of excisting architecture and new projects. For excisting architecture, se
Fixed

2021-06-29 06:57 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +	A global pipe, "global-person", has three source datasets, crm-person, hr-person and economy-person. The crm-person dataset has high quality work experience data and medium quality hours logged data
Fixed

2021-06-29 06:57 UTC, erik-leven commented on training/010_architecture_and_concepts/030_Novice.rst
> +The dataset hr-person does not contain any data regarding "hours-pr-project" or "weekly-hours-billed" and can therefore be left out of the prioritations.
Fixed now :D

2021-06-29 06:57 UTC, erik-leven commented on training/030_dtl/020_Beginner.rst
I see them in my file

2021-06-29 07:39 UTC, ga-hegsvold requested changes
This is very strange. Several of the things you see on your end is still missing on my end after I pull the latest changes from remote branch 246.
Have you tried `$ git pull origin training` from branch 246 before pushing to remote?

2021-06-29 07:39 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Since they are a relatively common way to store data, Sesam has a ready built-in connector for MSSQL databases. The MSSQL system inside Sesam connects to an MSSQL database by sending the host, databa
Oh no! typo: The "l" in mssql is missing.

2021-06-29 07:39 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +The dataset hr-person does not contain any data regarding "hours-pr-project" or "weekly-hours-billed" and can therefore be left out of the prioritations.
Very strange. It still says "prioritations" after I've pulled from branch 246.

2021-06-29 07:39 UTC, ga-hegsvold commented on training/030_dtl/020_Beginner.rst
Odd. Still missing on my end.

2021-06-29 07:39 UTC, ga-hegsvold commented on training/030_dtl/020_Beginner.rst
This one is also still missing on my end.

2021-08-18 11:58 UTC, gabriellsesam approved these changes

2021-08-18 13:46 UTC, ga-hegsvold approved these changes

2021-08-18 13:58 UTC, ga-hegsvold commented
I think Erik is preoccupied with training course, so I'll merge this one.

2021-08-18 13:58 UTC, merged