#235: Merge Architecture: Beginner: Datasets vs. tables to training
datanav/docs pull request #292
Opened 2021-06-03 08:47 UTC by ga-hegsvold

2021-06-03 10:46 UTC, JonasAls89 requested changes

2021-06-03 10:46 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  record is therefor not persisted, unless you design for it.
typo : therefore , kanskje bare : particular record is therefore not available, ....

2021-06-03 10:46 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  Sesam datasets will therefore grow as data changes, and all changes
Jeg ville sagt: as data changes, as all changes will be tracked.

2021-06-03 10:46 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  or enforces any integrity constraints on or between datasets.
Jeg ville ha omstrukturert disse to skildringer for schema. Start med å fortelle at Sesam datasets er schemaless, or dermed ikke har integrity constraints, deretter fortæl om tabeller i databaser som har integrity constraints. 

Da vil det kanskje også bli lettere for "beginners" å forstå hva der menes med "integrity constraints".

2021-06-03 10:46 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  do not have to spend any time on restructuring inboud data.
typo : inbound

2021-06-03 10:46 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  This also means that you as the integration specialist must take care of
jeg ville skrevet: specialist must define any relevant ... 

De ordene som står nå er lidt unødvendige.

2021-06-03 11:40 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  Sesam datasets will therefore grow as data changes, and all changes
when data changes, as all changes will be tracked.

2021-06-04 07:27 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  record is therefor not persisted, unless you design for it.
fixed

2021-06-04 07:28 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  Sesam datasets will therefore grow as data changes, and all changes
fixed, med en twist.

2021-06-04 07:42 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  or enforces any integrity constraints on or between datasets.
Ser poenget ditt, men har bevisst valgt å starte med tabeller for hvert punkt for å beskrive det "etablerte", for så å beskrive hvordan Sesam gjør det annerledes. Hvis rekkefølgen skal byttes på ett punkt, bør det byttes på alle.
Med tanke på at det bare er en kort setning om tabeller først, og at man raskt får mer uttrypende info i neste paragraf om datasett, kan det funke slik det er?

2021-06-04 07:42 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  do not have to spend any time on restructuring inboud data.
fixed

2021-06-04 07:43 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  This also means that you as the integration specialist must take care of
Enig. Fixed.

2021-06-04 09:26 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  or enforces any integrity constraints on or between datasets.
Det kan nok funke, men bange for at integrity contraints fortsatt bør forklares mere lav-praktisk.

2021-06-07 07:20 UTC, JonasAls89 approved these changes
Due to your integrity, I'll pre-approve this one as the constraints will be smoothened.

2021-06-07 09:31 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  or enforces any integrity constraints on or between datasets.
Har beskrevet integrity constraints i litt mer detalj under tabell-delen.

2021-06-08 14:27 UTC, mofsesam approved these changes
A nice read 👍 
You could argue that you can (but don't have to) use schemas with some connectors, but don't think this is very relevant in this scope.

2021-06-08 14:33 UTC, merged