#294 : Adding this section to Novice in Sesam In tha wild
datanav/docs pull request #295
Opened 2021-06-03 14:03 UTC by JonasAls89

2021-06-04 12:25 UTC, ga-hegsvold requested changes
Overall well written. The third paragraph is maybe a bit long. Consider breaking it up into a couple of smaller chunks if possible.

Besides that, see my comments.

2021-06-04 12:25 UTC, ga-hegsvold commented on training/060_sesam_in_the_wild/030_Novice.rst
> +The above description of the entity is a semantic categorization, as we define its meaning based on our understanding of the words that make up the entity. Albeit, from a semantic point of view, in t
The punctuation should be outside the formatting as it is not part of the Sesam config:
\``salesforce-person:EmployeeStatus.\`` --> \``salesforce-person:EmployeeStatus\``.

The combination of "This could" and "which will" in the sentence below doesn't feel quite right:

> This could for example be done by having a mapping dataset, which will contain a semantic description for a range of integers

I think it could be rephrased to:

> This could for example be done by having a mapping dataset containing a semantic description for a range of integers

2021-06-04 12:25 UTC, ga-hegsvold commented on training/060_sesam_in_the_wild/030_Novice.rst
> +      ["hops", {
Indentation is a bit off here..

2021-06-04 12:25 UTC, ga-hegsvold commented on training/060_sesam_in_the_wild/030_Novice.rst
> +And would produce the following changes to the dataset produced by the pipe ``salesforce-person:``
Same case as with punctuation above:
\``salesforce-person:\`` --> \``salesforce-person\``:

2021-06-04 12:25 UTC, ga-hegsvold commented on training/060_sesam_in_the_wild/030_Novice.rst
> +	  "salesforce-person:EmployeeStatusDescription": "On Leave",
Wouldn't ``EmployeeStatusDescription`` technically get its namespace from the mapping-dataset here since it's a ``merge``?

2021-06-04 12:25 UTC, ga-hegsvold commented on training/060_sesam_in_the_wild/030_Novice.rst
> +As can be seen from the above result, we are now able to tell that Tordenskjold Skipskaptajnson is currently "On Leave", which means that he should not be paid his monthly salary. In addition, this m
Funny! :-)

2021-06-04 12:25 UTC, ga-hegsvold commented on training/060_sesam_in_the_wild/030_Novice.rst
> +Tag your entities - Categorization of sub-concepts
I don't understand the "Tag your entities" part. What does that mean?

2021-06-07 07:16 UTC, JonasAls89 commented on training/060_sesam_in_the_wild/030_Novice.rst
> +Tag your entities - Categorization of sub-concepts
Not completely sure about the tag part either. But for now I'm gonna let it be.

2021-06-07 07:42 UTC, ga-hegsvold requested changes

2021-06-07 07:42 UTC, ga-hegsvold commented on training/060_sesam_in_the_wild/030_Novice.rst
> +      ["hops", {
Line 64 should be dedented to match line 72.

2021-06-07 07:42 UTC, ga-hegsvold commented on training/060_sesam_in_the_wild/030_Novice.rst
> +Tag your entities - Categorization of sub-concepts
Anyone else got input on this?

2021-06-07 08:02 UTC, JonasAls89 commented on training/060_sesam_in_the_wild/030_Novice.rst
> +      ["hops", {
fixed

2021-06-12 05:25 UTC, gabriellsesam commented on training/060_sesam_in_the_wild/030_Novice.rst
> +Tag your entities - Categorization of sub-concepts
Yea - when you have for example a table from your customer system called "cab-customer" and the data does not clearly define if the customer is government, private person or company then you can add logic either into the input pipe or the global which defines what "sub concept" the entities belong to, so you can easily filter in downstream pipes

2021-06-12 05:33 UTC, gabriellsesam commented
I like what you wrote here alot, and there is some overlap with the intent of this topic but not 100%.

I think we should rename this topic to "Mapping attributes across systems" - this would entail changing the case you've written here to include a second system which has it's own set of statuses and using the hop in a preparation pipe going to that third system. 

The mapping dataset should be called `sesam-map-salesforce-person-status` and the _id needs to be equivalent to the EmployeeStatus

2021-06-12 05:34 UTC, gabriellsesam commented on training/060_sesam_in_the_wild/030_Novice.rst
> +.. _tag-your-entities-categorization-of-sub-concepts-6-2:
Should be renamed to: Mapping the meaning of data across systems (?)

2021-06-12 05:35 UTC, gabriellsesam commented on training/060_sesam_in_the_wild/030_Novice.rst
> +	  "EmployeeStatus": 0,
Add: `"_id": "0",` to match the EmployeeStatus

2021-06-12 05:36 UTC, gabriellsesam commented on training/060_sesam_in_the_wild/030_Novice.rst
> +	  "salesforce-person:EmployeeStatus": 0,
Add or explain a `make-ni` on the `employeeStatus` attribute
`["make-ni", "sesam-map-salesforce-person-status", "EmployeeStatus"]`

2021-06-12 05:37 UTC, gabriellsesam commented on training/060_sesam_in_the_wild/030_Novice.rst
> +		["eq", "_S.salesforce-person:EmployeeStatus", "md.EmployeeStatus"]
`["eq", "_S.salesforce-person:EmployeeStatus-ni", "md.$ids"]`

2021-06-12 05:38 UTC, gabriellsesam commented on training/060_sesam_in_the_wild/030_Novice.rst
> +	      "datasets": ["mapping-dataset md"],
`"datasets": ["sesam-map-salesforce-person-status"],`

2021-06-12 05:39 UTC, gabriellsesam commented on training/060_sesam_in_the_wild/030_Novice.rst
> +	      "return": ["dict", "EmployeeStatusDescription", "md.Description"]
`"return": ["dict", "EmployeeStatusDescription", "md.sesam-map-salesforce-person-status:Description"]`

2021-06-14 08:52 UTC, ga-hegsvold requested changes
@gabriellsesam thanks for elaborating on the title and intention of this section.
I've added some questions and comments on your comments.

2021-06-14 08:52 UTC, ga-hegsvold commented on training/060_sesam_in_the_wild/030_Novice.rst
> +Tag your entities - Categorization of sub-concepts
@gabriellsesam this sounds like a sensible thing to do. Do you know of any general guidelines on how to do this?
Should we add new properties describing the "sub concepts"? Or maybe add new rdf:types?

In light of Gabriel's explanation of the title, is this text still on topic?
Even if it's not I do think we should keep it. Explaining how to use mapping datasets is very valuable, but maybe put it under another section? Something like "How to use mapping datasets"?

2021-06-14 08:52 UTC, ga-hegsvold commented on training/060_sesam_in_the_wild/030_Novice.rst
> +	  "salesforce-person:EmployeeStatus": 0,
@gabriellsesam 
I generally agree on this, but the "sesam" part of the mapping dataset feels a bit redundant. Is there a situation where we would prefix with something other than "sesam"? Maybe "map-salesforce-person-status" is sufficient?

2021-06-16 07:58 UTC, JonasAls89 commented on training/060_sesam_in_the_wild/030_Novice.rst
> +	  "salesforce-person:EmployeeStatus": 0,
I feel like it's a bit unintended to add a make-ni towards a mapping dataset...? I'll not add the "make-ni" until it's been clarified. To my knowledge the main purpose of "make_ni" is to mimic foreign-keys from relational databases. Adding it for a mapping dataset we create artificially feels a bit redundant to me. @ga-hegsvold , @gabriellsesam

2021-06-16 08:03 UTC, JonasAls89 commented on training/060_sesam_in_the_wild/030_Novice.rst
> +.. _tag-your-entities-categorization-of-sub-concepts-6-2:
chose to go with: Creating mapping data for enrichment

2021-06-16 10:38 UTC, ga-hegsvold reviewed
Add my thoughts.

2021-06-16 10:38 UTC, ga-hegsvold commented on training/060_sesam_in_the_wild/030_Novice.rst
> +	  "salesforce-person:EmployeeStatus": 0,
I view make-ni as a tool to help connect data. It's probably safe to say that in most cases it's used the way you describe, @JonasAls89, but I don't see anything wrong with using make-ni in other cases as well, as long as it eases the job of connecting data.
I've seen examples of database tables where no PKs or FKs where defined at all, but the intention was clearly to have certain fields operate as PKs and FKs. In this case it would make sense to use make-ni on the fields intended as FKs.

When it comes to mapping datasets, it can sometimes be beneficial to use make-ni, but not always.
In some cases it's not practical to use the _id / $ids as equality criteria. Sometimes it's much easier to just use values as-is without introducing namespaces in the property values.
There can also be cases where you want to reuse a mapping, but match on different properties in the mapping dataset.
In these cases I would not bother with using make-ni.

In this particular example I don't think it's strictly necessary to use make-ni.
You could argue that the status code mapping in this example could be reused by multiple sources.
So to map status from salesforce you could do lookup on a "salesforce-status-code" property in the mapping dataset.
To map from crm you could do lookup on a "crm-status-code" property, etc.
And in all cases you could return the "description" property.

2021-06-16 10:38 UTC, ga-hegsvold commented on training/060_sesam_in_the_wild/030_Novice.rst
> +		["eq", "_S.salesforce-person:EmployeeStatus", "md.EmployeeStatus"]
Sesam will actually give you $ids implicitly behind the scenes even if that property is not visible on the entity.
Since it's not obvious where the $ids property comes from here, we may not want to use it in this example.

2021-08-18 14:20 UTC, ga-hegsvold commented
Fixed merge conflict.

2021-09-08 08:26 UTC, gabriellsesam commented on training/060_sesam_in_the_wild/030_Novice.rst
> +	  "salesforce-person:EmployeeStatus": 0,
Your arguments make sense, make-ni in this instance would be a bit arbitrary

2021-09-08 08:27 UTC, gabriellsesam commented on training/060_sesam_in_the_wild/030_Novice.rst
> +		["eq", "_S.salesforce-person:EmployeeStatus", "md.EmployeeStatus"]
Yeah, in general i prefer hopping to the $ids as it makes indexing a non-issue, but to do so we need a pre-defined foreign key (which we wont do in this topic) so it is fine as is

2021-09-08 08:31 UTC, gabriellsesam approved these changes

2021-09-24 13:06 UTC, ga-hegsvold requested changes

2021-09-24 13:06 UTC, ga-hegsvold commented on training/060_sesam_in_the_wild/030_Novice.rst
> +Which could be semantically defined as an object which is concerned with personal data. This definition is a very general one, as personal data can be many things. Meanwhile, for this specific entity
"Which could be" - what does "Which" refer to? Could it be re-written as "This entity could be"?

2021-09-28 08:15 UTC, ga-hegsvold approved these changes

2021-09-30 12:06 UTC, merged