#302: Update README.md to include a styleguide
datanav/docs pull request #303
Opened 2021-06-12 06:19 UTC by gabriellsesam

2021-06-14 07:50 UTC, ga-hegsvold requested changes
Very nice! Just one comment regarding hard-coded numbering.

2021-06-14 07:50 UTC, ga-hegsvold commented on training/README.md
> +alternative text is prefixed with the numbering "Figure 2".
I think we should omit hard-coded numbering for now.

2021-06-14 09:45 UTC, ga-hegsvold approved these changes

2021-08-24 08:41 UTC, mofsesam approved these changes
Looks sensible, but GA approving is most important :)

2021-09-01 10:44 UTC, merged