#250 : Adding change tracking and data delta
datanav/docs pull request #305
Opened 2021-06-17 13:43 UTC by JonasAls89

2021-06-17 15:15 UTC, ga-hegsvold requested changes
Mostly good. Some comments as always. ;-)

2021-06-17 15:15 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +	1) When reading data from a source system, it may be possible to just ask for the data that have changed since the last time, if the source supports it. This mechanism uses entries from the source,
We can use # instead of hard-coded numbers to make dynamically numbered lists.
Indentation is also handled automatically.

---

It's a good practice to start with the condition, and then explain what happens if the condition is true (if this, then that).
Then we avoid surprising the readers with everything they read up to this point only applies if...

So suggested restructuring of this sentence:

> When reading data from a source system, it may be possible to just ask for the data that have changed since the last time, if the source supports it.

and put the "if ..."-part at the very start or right after the "When ..."-part.

2021-06-17 15:15 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +	2) Secondly, the first time data flows through a pipe in Sesam that pipe's dataset will be created. Datasets consist of entities and on each entity a ``hash`` property will be created. This ``hash``
"Secondly" can be omitted since we already have a numbered list and the previous list item does not start with "Firstly".

---

\``hash\`` --> \``_hash\``

---
Suggestion:

> Datasets consist of entities and on each entity a \``hash\`` property will be created.

-->

> Datasets consist of entities and each entity has a \``_hash\`` property.

Should we explain which properties are used as base for the hashing or should that be covered in a higher learning tier?

2021-06-18 05:35 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +Change tracking and data delta allows for Sesam to process and update data only when it changes. This ensures minimal latency and increases agility when 1)reading data from a source system and 2) whe
Implementing. with regards to numbering, that was the intent indeed.

2021-06-18 05:42 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +	2) Secondly, the first time data flows through a pipe in Sesam that pipe's dataset will be created. Datasets consist of entities and on each entity a ``hash`` property will be created. This ``hash``
I wasn't quite sure there, eventually I thought that would be a good subject down the road. @gabriellsesam  any thoughts?

2021-06-18 08:25 UTC, ga-hegsvold requested changes
Small typo I missed on the first read and another suggestion.

2021-06-18 08:25 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +Firstly, when reading data from a source system, if the source supports it, it may be possible to just ask for the data that have changed since the last time. This mechanism uses entries from the sou
Much better. Reading two "it"s in a row can break the flow a bit. To avoid this it can be rephrased from:
> if the source supports it

to:

> if supported by the source

2021-06-18 08:25 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +Secondly, the first time data flows through a pipe in Sesam that pipe's dataset will be created. Datasets consist of entities and on each entity a ``_hash`` property will be created. This ``_hash`` p
typo: "recoqnizes" --> "recognizes"

2021-06-18 13:16 UTC, ga-hegsvold approved these changes
There are a couple of unresolved questions, but I'll leave it to others to comment further.

2021-08-18 11:16 UTC, gabriellsesam commented on training/010_architecture_and_concepts/030_Novice.rst
> +	2) Secondly, the first time data flows through a pipe in Sesam that pipe's dataset will be created. Datasets consist of entities and on each entity a ``hash`` property will be created. This ``hash``
I think we can just reference "Docs/Developer Guide/Entity Data Model"

2021-08-18 11:44 UTC, gabriellsesam approved these changes
See latest commit for minor changes, added see also section for _hash, change tracking etc

2021-08-20 07:12 UTC, merged