Add custom CSS support
datanav/docs pull request #306
Opened 2021-06-22 14:21 UTC by ga-hegsvold

- Add _templates/css/sesam.css to contain custom CSS
- Update _templates/layout.html to use custom CSS
- Update README.md with custom CSS setup and usage instructions

2021-06-22 14:39 UTC, gabriellsesam approved these changes

2021-06-23 06:19 UTC, JonasAls89 requested changes

2021-06-23 06:19 UTC, JonasAls89 commented on training/README.md
> +With the custom CSS in the expected folder, `_templates/layout.html` is now able include it when building
typo: is now able to include it when ... Du mangler "to" i setningen

2021-06-23 06:19 UTC, JonasAls89 commented on training/README.md
>  Numbering is added in post as the docs page is generated. We use the toctree flag :numbered: in training.rst to enable this.
toctree eller doctree ?

2021-06-23 07:15 UTC, ga-hegsvold commented on training/README.md
> +With the custom CSS in the expected folder, `_templates/layout.html` is now able include it when building
fixed

2021-06-23 07:17 UTC, ga-hegsvold commented on training/README.md
>  Numbering is added in post as the docs page is generated. We use the toctree flag :numbered: in training.rst to enable this.
Skrev ikke om dette nå, men "toctree" er nok riktig. Står for "table of contents tree".

2021-06-23 07:17 UTC, JonasAls89 commented on training/README.md
>  Numbering is added in post as the docs page is generated. We use the toctree flag :numbered: in training.rst to enable this.
Takk for forklaringen.

2021-06-23 07:18 UTC, JonasAls89 approved these changes

2021-06-23 07:30 UTC, merged