#201: Merge "Systems: Beginner" to training
datanav/docs pull request #309
Opened 2021-06-24 13:34 UTC by ga-hegsvold

2021-06-25 06:30 UTC, JonasAls89 requested changes

2021-06-25 06:30 UTC, JonasAls89 commented on training/020_systems/020_Beginner.rst
> +
Think we can omit this yes.

2021-06-25 06:30 UTC, JonasAls89 commented on training/020_systems/020_Beginner.rst
> +    "url_pattern": "https://ws.geonorge.no/kommuneinfo/v1/%s"
Du mangler komma "," etter "url_pattern"

2021-06-25 06:30 UTC, JonasAls89 commented on training/020_systems/020_Beginner.rst
> +    "url_pattern": "$ENV(difi-api)"
"," komma igjen

2021-06-25 06:30 UTC, JonasAls89 commented on training/020_systems/020_Beginner.rst
> +Or should we just reference the docs?
Ref the docs.

2021-06-25 07:04 UTC, ga-hegsvold commented on training/020_systems/020_Beginner.rst
> +    "url_pattern": "https://ws.geonorge.no/kommuneinfo/v1/%s"
fixed

2021-06-25 07:04 UTC, ga-hegsvold commented on training/020_systems/020_Beginner.rst
> +    "url_pattern": "$ENV(difi-api)"
fixed

2021-06-25 07:06 UTC, JonasAls89 approved these changes

2021-08-18 11:15 UTC, gabriellsesam approved these changes
See latest commit for my changes

2021-08-18 12:54 UTC, merged