#308: Merge Architecture: Beginner: Systems into training
datanav/docs pull request #322
Opened 2021-07-07 13:51 UTC by ga-hegsvold

#308: Tidy up Architecture & Concepts: Beginner: Systems

2021-07-07 13:54 UTC, ga-hegsvold commented
FYI: Summary and references to other sections will be added in #310. Skipping them here to avoid conflicts.

2021-08-18 09:58 UTC, JonasAls89 requested changes

2021-08-18 09:58 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Systems are therefore the start and end points of every integration flow.
dataflow? blir det vel. Ikke integration flow

2021-08-18 13:06 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/020_Beginner.rst
> +Systems are therefore the start and end points of every integration flow.
Fixed.

2021-08-18 13:14 UTC, JonasAls89 approved these changes

2021-08-18 15:31 UTC, gabriellsesam approved these changes

2021-08-19 06:59 UTC, merged