#312: Merge Microservices: Beginner: What is a microservice? to training
datanav/docs pull request #323
Opened 2021-07-08 08:12 UTC by ga-hegsvold

2021-07-08 08:26 UTC, JonasAls89 approved these changes
short and concise

2021-08-18 10:27 UTC, JonasAls89 requested changes

2021-08-18 10:27 UTC, JonasAls89 commented on training/050_microservices/020_Beginner.rst
> +  - confgured and monitored as Sesam Systems
typo : configured

2021-08-18 11:02 UTC, gabriellsesam approved these changes

2021-08-18 13:12 UTC, JonasAls89 approved these changes

2021-08-18 13:13 UTC, merged