#313: Merge Why use Microservices in Sesam? into training
datanav/docs pull request #324
Opened 2021-07-08 08:46 UTC by ga-hegsvold

Previous version of this branch was based off of branch 312.
This one is branched of off training to make it more independent.

2021-07-08 13:49 UTC, JonasAls89 requested changes

2021-07-08 13:49 UTC, JonasAls89 commented on training/050_microservices/020_Beginner.rst
> +tweak it a bit  to fit your needs, or simply write your own from scratch.
double spacing

2021-07-08 13:52 UTC, ga-hegsvold commented on training/050_microservices/020_Beginner.rst
> +tweak it a bit  to fit your needs, or simply write your own from scratch.
fixed!

2021-07-08 14:04 UTC, JonasAls89 approved these changes

2021-08-18 11:00 UTC, gabriellsesam approved these changes

2021-08-18 13:16 UTC, merged