#317 : Adding Categories of Microservices for Beginners
datanav/docs pull request #331
Opened 2021-08-20 06:38 UTC by JonasAls89

Correcting error on ref line inn Systems -> Beginner.rst file when making seealso section on this PR.

2021-08-20 07:28 UTC, ga-hegsvold requested changes
Nice! I just have a comment about the term "figurate".

2021-08-20 07:28 UTC, ga-hegsvold commented on training/050_microservices/020_Beginner.rst
> +Both internal microservices and external microservices will figurate in a Sesam node as systems. However, microservices that connect to a Sesam node via the `Service API <https://docs.sesam.io/api.ht
Is "figurate" a good term to use here? https://www.dictionary.com/browse/figurate

Can we use "be defined" instead?

2021-08-20 07:28 UTC, ga-hegsvold commented on training/050_microservices/020_Beginner.rst
> +Even though external microservices figurate in Sesam as systems, they do not read or write data into or out of Sesam with regards to a defined dataflow. Rather, they implement their functionality in
"figurate"? - see comment above.

2021-08-20 07:41 UTC, JonasAls89 commented on training/050_microservices/020_Beginner.rst
> +Even though external microservices figurate in Sesam as systems, they do not read or write data into or out of Sesam with regards to a defined dataflow. Rather, they implement their functionality in
Oppdatert.

2021-08-20 07:56 UTC, ga-hegsvold requested changes
One "figurate" remaining on my end... See below.

2021-08-20 07:56 UTC, ga-hegsvold commented on training/050_microservices/020_Beginner.rst
> +Even though external microservices figurate in Sesam as systems, they do not read or write data into or out of Sesam with regards to a defined dataflow. Rather, they implement their functionality in
Hm.. Still says "figurate" here on my end... Are all changes pushed?

2021-08-20 08:06 UTC, JonasAls89 commented on training/050_microservices/020_Beginner.rst
> +Even though external microservices figurate in Sesam as systems, they do not read or write data into or out of Sesam with regards to a defined dataflow. Rather, they implement their functionality in
missed that one. two sec

2021-08-20 08:17 UTC, ga-hegsvold approved these changes
See my comment below. It's a nit-pick. Adjust if you agree. I'll approve regardless.

2021-08-20 08:17 UTC, ga-hegsvold commented on training/050_microservices/020_Beginner.rst
> +Both internal microservices and external microservices will be defined in a Sesam node as systems. However, microservices that connect to a Sesam node via the `Service API <https://docs.sesam.io/api.
This is not a big deal but I think it will improve the flow of reading a bit: At the beginning of this sentence, the repetition of "microservices" after both "internal" and "external" is not needed.
"Both internal and external microservices..." flows a bit better, I think.

2021-08-20 08:37 UTC, JonasAls89 commented on training/050_microservices/020_Beginner.rst
> +Both internal microservices and external microservices will be defined in a Sesam node as systems. However, microservices that connect to a Sesam node via the `Service API <https://docs.sesam.io/api.
onn its way :yoda:

2021-08-20 09:12 UTC, gabriellsesam commented on training/050_microservices/020_Beginner.rst
> +Both internal and external microservices will be defined in a Sesam node as systems. However, microservices that connect to a Sesam node via the `Service API <https://docs.sesam.io/api.html>`_ can al
`Both internal and external microservices will be defined in a Sesam node as systems.`
external microservices do not need to be defined in a Sesam node as systems, they can be run outside of Sesam also.

2021-08-20 09:16 UTC, gabriellsesam requested changes
I want this section to make it clear that External microservices can run outside of a Sesam node, otherwise very well written.

2021-08-20 09:16 UTC, gabriellsesam commented on training/050_microservices/020_Beginner.rst
> +Even though external microservices are defined in Sesam as systems, they do not read or write data into or out of Sesam with regards to a defined dataflow. Rather, they implement their functionality
```
Even though external microservices are defined in Sesam as systems, they do not...
```
I would rephrase to (building on my last comment)
```
External microservices can be hosted inside your Sesam node as a system or outside of your Sesam node in your preferred docker-compatible solution like for example Kubernetes.
They do not ...
```

2021-08-20 09:39 UTC, JonasAls89 commented on training/050_microservices/020_Beginner.rst
> +Both internal and external microservices will be defined in a Sesam node as systems. However, microservices that connect to a Sesam node via the `Service API <https://docs.sesam.io/api.html>`_ can al
On its way! 👍

2021-08-24 07:40 UTC, gabriellsesam approved these changes

2021-08-24 07:41 UTC, merged

2021-08-24 08:00 UTC, mofsesam approved these changes
I have no problem with the changes, but in more general I wonder in the introduction of concepts of internal and external microservices helps a beginner.