#319 : Adding tasks for Beginners.
datanav/docs pull request #335
Opened 2021-08-25 11:32 UTC by JonasAls89

Not sure whether more tasks are needed for beginners?

2021-08-25 13:53 UTC, ga-hegsvold requested changes
Good! Just a small suggestion.

2021-08-25 13:53 UTC, ga-hegsvold commented on training/050_microservices/020_Beginner.rst
> +#. *What is a microservice in Sesam?*
Suggestion: Switch the order of the first two tasks so that the reader first defines what a microservice is, and then explains why it's used in Sesam.

2021-08-25 14:02 UTC, ga-hegsvold approved these changes
Nice! This is good start. More tasks can be added later if needed.

2021-09-01 10:43 UTC, gabriellsesam approved these changes

2021-09-01 10:43 UTC, merged