#345 : Adding sesam-CLI section
datanav/docs pull request #357
Opened 2021-09-06 13:18 UTC by JonasAls89

Not the comment in the see-also section, not exactly sure which other sections I should point to as this is a fairly narrow and compressed scope.

2021-09-06 13:48 UTC, ga-hegsvold requested changes

2021-09-06 13:48 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
A few suggestions:
- Sesam client git repo
- Sesam client docs (https://docs.sesam.io/sesam-client.html)
- Working on a Sesam project (https://docs.sesam.io/project-workflow.html)

2021-09-06 13:48 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
Could you also add a summary?
For instance a one-liner for each of the most used sesam client commands.
Keep in mind this will end up on a Training slide.

2021-09-06 13:48 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +Starting using the Sesam CLI on a project you should verify your local copy of the node config located on GitHub is up to date with recent changes. This is a rule of thumb when collaborating on a giv
Can you format the 1), 2), 3) steps as a list? A bit easier to read.

2021-09-06 13:48 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +In addition to all of the above, you should create an ``/expected`` folder. This folder should be placed in the root of your already existing ``/node`` folder. The ``/expected`` folder will hold all
A neat trick to mention here is that `sesam update` creates the `expected` folder with template test configs for you.
Also be careful with the `/` in front of folders. This indicates that the folders are on the root level of the file system.
I suggest using `folder-name/` instead and be clear where in the folder hierarchy we're referencing.

2021-09-06 14:02 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +Starting using the Sesam CLI on a project you should verify your local copy of the node config located on GitHub is up to date with recent changes. This is a rule of thumb when collaborating on a giv
It might also be worth pointing out that the very first time you start using the sesam client in an existing project, you first clone the project repo, configure `.syncconfig` and run `sesam test` (or `sesam wipe` then `sesam test`) to sync your node.
I couldn't find this described anywhere else in our docs.

2021-09-07 05:11 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/020_Beginner.rst
Nice GAH

2021-09-07 05:12 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/020_Beginner.rst
Will do.

2021-09-07 05:14 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +Starting using the Sesam CLI on a project you should verify your local copy of the node config located on GitHub is up to date with recent changes. This is a rule of thumb when collaborating on a giv
Can you elaborate on this? Long since I did it and I cannot immediately see how `sesam test` would sync a node @ga-hegsvold ?

2021-09-07 05:14 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +In addition to all of the above, you should create an ``/expected`` folder. This folder should be placed in the root of your already existing ``/node`` folder. The ``/expected`` folder will hold all
Brilliant!

2021-09-07 07:26 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +Starting using the Sesam CLI on a project you should verify your local copy of the node config located on GitHub is up to date with recent changes. This is a rule of thumb when collaborating on a giv
Sure. The first time you start working on a project you presumably don't have any configs locally or in you dev node yet.
By cloning the repo, configuring `.syncconfig` and running `sesam test`, your node will be in sync with the repo.

2021-09-07 14:03 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +Starting using the Sesam CLI on a project you should verify your local copy of the node config located on GitHub is up to date with recent changes. This is a rule of thumb when collaborating on a giv
Thanks GAH

2021-09-08 08:53 UTC, gabriellsesam commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +The Sesam command line interface (CLI) is used in order to support continous integration/continous deployment (CICD) workflows. This is especially handy when multiple people are involved with working
`This is especially handy when multiple people are involved with working`
->
`This is especially handy when multiple people are working`


`does continous changes to specific workflows asyncronously.`
->
`changes the node configuration when they want to.`

`assessible` -> `accessible` or `assessable` (?)

```
Typically, GitHub is used to make a Sesam node config assessible from multiple different local instances of a Sesam node.  
```
->
```
The Sesam node configuration is typically stored in GitHub to make it accessible & version controlled.
```

2021-09-08 08:55 UTC, gabriellsesam commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +  2) Wipe your local node by running: ``sesam wipe``.
Local node is misleading and technically wrong unless you actually host your own node.
I would use the name "Dev Node"

2021-09-08 08:56 UTC, gabriellsesam commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +  3) Run ``sesam upload`` to upload your local node config to your Sesam node, accessible in your preferred browser.
`to your Sesam node`
->
`to your Dev Node`

2021-09-08 08:58 UTC, gabriellsesam commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +In addition to all of the above, you should create an ``expected/`` folder. The preferred way of doing this is to run ``sesam update`` which will create the ``expected/`` folder with template test co
```
When finished with making local node config changes, then run ``sesam download`` followed by ``sesam test``
```
Very confusing that "local node config changes" actually mean "changes on your dev node" in this sentence.
If somebody does "local node config changes" meaning changes in their local version of the repo followed by "sesam download" all their changes would be lost.

2021-09-08 09:18 UTC, gabriellsesam commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +  **Note**: Remember to run ``sesam download`` to save your current local sesam node config, if you want to retain those changes before running ``sesam wipe`` as ``sesam wipe`` will not save your cur
```
  **Note**: Remember to run ``sesam download`` to save your current local sesam node config, if you want to retain those changes before running ``sesam wipe`` as ``sesam wipe`` will not save your current node config for you.
```
```
  **Note**: Remember to run ``sesam download`` to download your dev node configuration before wiping it with ``sesam wipe``, but note that running ``sesam download`` will remove any changes you have in your local repo which are not already uploaded to your dev node.
```

2021-09-08 09:27 UTC, gabriellsesam requested changes
I think some phrases used in this topic like  "local sesam node" &  "local sesam node configuration" make it very confusing to seperate what is what, especially for a beginner.

Many sentences need some cleanup and I advice we both include this kind of vocabulary and replace references in this topic like "local sesam node instance" with "dev node"
```
Nodes
* Prod & Test Nodes: The Sesam nodes which actually run in prod/test environments.
* Dev node: Your private node used for development purposes.
Git:
* Git repo: The git repo which stores the Prod & Test Nodes configurations.
* Local git repo: Your local version of the git repo with a `.syncconfig` file connected to your Dev node.
* Remote Git repo: The git repo as seen from it's webpage.
```

2021-09-08 10:18 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +  **Note**: Remember to run ``sesam download`` to save your current local sesam node config, if you want to retain those changes before running ``sesam wipe`` as ``sesam wipe`` will not save your cur
Thanks for "on point" feedback Gabbe! Will implement and alter. 👍

2021-09-08 11:00 UTC, gabriellsesam approved these changes

2021-09-17 08:13 UTC, ga-hegsvold approved these changes

2021-09-24 06:05 UTC, merged