346 : Adding section about testdata and testing
datanav/docs pull request #359
Opened 2021-09-09 11:10 UTC by JonasAls89

2021-09-28 12:57 UTC, ga-hegsvold requested changes

2021-09-28 12:57 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +When the above pipe completes a run, given that the property ``"condition": "$ENV(node-env)"`` equals ``"condition": "test"`` and **not** ``"condition": "prod"``, it will only see the data that is de
Can you put the **Note** in a `.. note::` directive? Makes it stand out a bit more.

2021-10-04 07:32 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +  - ensure changes made are robust enough to be pushed to production
I've always used the "-" to prefix in this summary section..?

2021-10-04 07:35 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +Extending on the testing aspect of running your CI/CD workflows via the Sesam CLI - testdata comes into play. In practice, testing via the Sesam CLI uses testdata defined in your Sesam development no
implemented.

2021-10-04 07:37 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +To use testdata in Sesam, you will first need to create it. In order for you to do so, Sesam has developed a nifty transformation rule called the ``conditional`` transform statement. An example of a
I see your point, albeit I'm not sure we need this level of detail here.. Any thoughts @gabriellsesam ?

2021-10-04 07:39 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +When the above pipe completes a run, given that the property ``"condition": "$ENV(node-env)"`` equals ``"condition": "test"`` and **not** ``"condition": "prod"``, it will only see the data that is de
implemented

2021-10-04 12:43 UTC, ga-hegsvold requested changes
Clarified my comments.

2021-10-04 12:43 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +  - ensure changes made are robust enough to be pushed to production
Ah, it's not about the bullet formatting, it's about the -ing form of the words. :-)
Each bullet point should be read as a correct sentence. The last two are not currently correct sentences:
> Testing and testdata is used for *validate* dataflows run as expected
> Testing and testdata is used for *ensure* changes made are robust enough to be pushed to production

2021-10-04 12:43 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +  Tools > Sesam Client :ref:`concepts-sesam-client`
Can you add a `:` before the ref so that it's a bit easier to see where the "bread crumbs" end and the ref starts?
I think we've tried to be consistent on that in other sections.

> Tools > Sesam Client: ...

2021-10-04 12:43 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +  Best Practices > Working on a Sesam Project :ref:`setting-up-a-new-sesam-project`
`:` before the ref

> Best Practices > Working on a Sesam Project: ...

2021-10-05 09:33 UTC, ga-hegsvold approved these changes

2021-10-05 10:40 UTC, merged