#348 : Adding JWT section
datanav/docs pull request #365
Opened 2021-09-27 06:53 UTC by JonasAls89

2021-09-28 08:45 UTC, ga-hegsvold requested changes

2021-09-28 08:45 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +A JSON Web Token (JWT) is an open standard that is a compact and self-contained means of securely transmitting information between parties as a JSON object, i.e: A user and a Sesam node. JWTs, from a
I think it's important to distinguish between authentication and authorization here:
_Authentication_ is the process of verifying that a party is who they claim to be.
_Authorization_ is the process of verifying the access rights of a party.

As far as I know a user must first be _authenticated_ by logging in to a Sesam node before he/she can generate a JWT.
Then the JWT can be used as _authorization_ to access different parts of the node.

So JWTs are not used for authentication, but for authorization after authentication have been confirmed.

Thoughts?

2021-09-28 08:45 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
>  JWT/Authentisering
Funny title ;-) Maybe just remove "Authentisering".

2021-09-30 12:05 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +A JSON Web Token (JWT) is an open standard that is a compact and self-contained means of securely transmitting information between parties as a JSON object, i.e: A user and a Sesam node. JWTs, from a
good point GAH. Will change accordingly.

2021-10-04 08:06 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +A JSON Web Token (JWT) is an open standard that is a compact and self-contained means of securely transmitting information between parties as a JSON object, i.e: A user and a Sesam node. JWTs, from a
Implemented

2021-10-04 12:57 UTC, ga-hegsvold requested changes
I think this is good. Just a couple of tiny adjustments under `.. seealso`.

2021-10-04 12:57 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +  Developer Guide > Service API :ref:`api-top`
Can you add ":" before the ref (same as for "Sesam in the Wild" above)?
The title of the referred section is "Service API" so you can skip hard coding it. Shows up twice now.

2021-10-04 12:57 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +  Tools > Databrowser :ref:`databrowser_ini_authorization_via_jwt_token`
Can you add ":" before the ref?

2021-10-04 14:11 UTC, ga-hegsvold approved these changes

2021-10-05 05:12 UTC, merged