#349 : Adding section on permissions
datanav/docs pull request #373
Opened 2021-10-04 10:34 UTC by JonasAls89

2021-10-04 14:02 UTC, ga-hegsvold requested changes
Looong comment here. ;-)

2021-10-04 14:02 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/020_Beginner.rst
Please include `.. seealso:` and link to https://docs.sesam.io/security.html.

2021-10-05 05:49 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +In a Sesam node you will have a set of hardcoded node permissions immediately available to you. Permissions are used to group users of a Sesam node into logical groups that have a controlled set of p
Thanks for the feedback @ga-hegsvold. Also found the topic poorly documented in the docs. Since they are "roles" that sounds fine to me, although it is a little inconsistent that they are prefixed with group: in the UI.

I'll add your changes and suggestions shorty.

2021-10-05 05:50 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/020_Beginner.rst
> +In a Sesam node you will have a set of hardcoded node permissions immediately available to you. Permissions are used to group users of a Sesam node into logical groups that have a controlled set of p
I will change the title of this section as well, since groups will not be used in the intended way.

2021-10-05 09:56 UTC, ga-hegsvold reviewed
I think this is a good overview of how permissions work in Sesam. I like how you managed to cover the levels of permissions without going into too much detail.

Any thoughts on what to include in a summary?
Maybe a short explanation of Members, Roles and Permissions?

Just to get started:
Members are users with access to the Sesam node.
Roles are used to group members with equal permissions.
Permissions are used to grant or restrict access to various parts of a Sesam node.

Something like this? Feel free to add/modify.

2021-10-05 13:01 UTC, merged