Added a section regarding the creation of new _id's
datanav/docs pull request #386
Opened 2021-10-13 10:59 UTC by TarjeiSkrede

We sometimes see pipes where a new _id field is created, which may cause wrong processing of entities, I have tried to add a new small section to address this.

2021-10-14 05:46 UTC, JonasAls89 requested changes
Well written. Added some view points.

2021-10-14 05:46 UTC, JonasAls89 commented on data-modelling.rst
> +If it is necessary to create a new '_id' for an entity it should then be created before any filters are applied to the transform and no values from joines entities should be used as part of the new i
typo: joined

do not know what is the standard in the docs, but in Sesambook we use ``_id``. as in code format when something refers to the config of an object in Sesam.

2021-10-14 05:46 UTC, JonasAls89 commented on data-modelling.rst
> +There is one important thing to be aware of when changing the value of the '_id' field. Any transforms or operations prior to the change of the '_id', will adhere to the original identity of the enti
can you maybe clarify where you are when you explain the issue, i.e: upstream from your current pipe or downstream from your current pipe, when the "error" might occur.

2021-10-14 08:45 UTC, TarjeiSkrede commented on data-modelling.rst
> +There is one important thing to be aware of when changing the value of the '_id' field. Any transforms or operations prior to the change of the '_id', will adhere to the original identity of the enti
The error will occur in the current pipe and resulting dataset, not in the upstream or downstream pipe. Don't feel that is so unclear.

2021-10-19 13:50 UTC, grove approved these changes

2021-10-19 13:50 UTC, merged