#432 : Adding section
datanav/docs pull request #485
Opened 2021-12-02 07:56 UTC by JonasAls89

Recognized that we lacked some mention of RDF in architecture and concepts Novice. Also added additional information in architecture and concepts Beginner. I think this turned out better than initially outlined with regards to our explanation of RDF.

2022-01-10 11:18 UTC, ga-hegsvold requested changes

2022-01-10 11:18 UTC, ga-hegsvold commented on training/010_architecture_and_concepts/030_Novice.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I'm not sure I understand the intention of this section.
The current content is essentially the same as this section: https://docs.sesam.io/rdf-support.html. We should avoid duplication.
What do we mean by "theoretical approach to semantics"?

2022-01-10 11:18 UTC, ga-hegsvold commented on training/030_dtl/030_Novice.rst
> +	:ref:`learn-sesam` > :ref:`architecture_and_concepts` > :ref:`architecture-and-concepts-novice-1-2` > :ref:`sesams-theoretical-approach-to-semantics-RDF-1-2`
fix indentation

2022-01-10 11:18 UTC, ga-hegsvold commented on training/030_dtl/030_Novice.rst
> +	  "_id": "mssql-accounts",
Consider renaming the pipe `_id` to align more with Sesam's best practices: Avoid using database type (ex: mssql) as id, rather use database name (ex: agresso/salesforce/..).

2022-01-10 12:55 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mhh.. Thought about that when adding it... Will try to contain myself to only new information, and then rather refer to what is already written in docs.

This is to ensure that a user will learn why our semantics (namespaces and NI's) look as they do. Also why it says theoretical, because this is the theory (URI, CURIE, N-Triples etc) that allows Sesam to implement the RDF standard.

2022-01-10 12:56 UTC, JonasAls89 commented on training/010_architecture_and_concepts/030_Novice.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* that is the RDF standard, I should have said.

2022-01-17 11:48 UTC, ga-hegsvold requested changes

2022-01-17 11:48 UTC, ga-hegsvold commented on training/030_dtl/030_Novice.rst
> +
The RDF explanation is already covered in Architecture and Concepts. This section should focus on `rdf:type` specifically.
A few points I think should be explained here:
- What are rdf:types in Sesam?
- How do we decide on the value of rdf:types? (source system id + business type from source)
- At what step in a dataflow are rdf:types normally added? ("enrichment" step)
- Why add rdf:types? - i.e. what are they used for in Sesam? (easily identify source system and business type, suitable for filtering, more?)

I don't have good answers for all this, but I feel the use of rdf:types in Sesam needs a more in-depth explanation than what we currently have in the docs.

2022-01-18 07:13 UTC, JonasAls89 commented on training/030_dtl/030_Novice.rst
> +
I see your point here and is implementing, as I'm typing this, albeit I do very much agree we must include the steps defined in a sesam dataflow, I'm a little reluctant to start introducing it, enrichment, now, as this is opening up "pandoras box"... ;)

I'm not completely sure what has been decided with regards to the structure of the Sesambook, albeit I believe we should have these steps play a central part in it.

2022-01-19 08:14 UTC, gabriellsesam approved these changes
I don't fully understand Sesams use of RDF myself, but I find this topic nicely explains how it relates to namespaces and rdf:type.

Expanding it beyond these attributes may open up pandoras box as you say and make the topic less practical, so I think what's written here is good.

2022-01-19 09:32 UTC, ga-hegsvold approved these changes

2022-01-19 09:32 UTC, ga-hegsvold commented on training/030_dtl/030_Novice.rst
> +
I see what you mean. Let's keep this section as it is for now then, but let's not forget that `rdf:type` and its purpose in Sesam should be explained in more detail somewhere in the docs.

2022-01-19 13:20 UTC, merged