added draft on patterns discussed so far
datanav/docs pull request #512
Opened 2021-12-18 01:58 UTC by BaardBouvet

2022-02-16 06:27 UTC, JonasAls89 requested changes
Some suggestions.

2022-02-16 06:27 UTC, JonasAls89 commented on patterns.rst
> +latest.
this sentence must be reformulated. Makes little sense as is.

2022-02-16 06:27 UTC, JonasAls89 commented on patterns.rst
> +Source sometimes produces an empty array for some reason (during restarts, authenticaion problems, etc). Use circuit breakers.
add ref:`circuit breakers <concepts-circuit-breakers>` link here maybe?

2022-02-16 06:27 UTC, JonasAls89 commented on patterns.rst
> +other sources. Time is not a good candidate for NI. Postnummer is an example. If you make a ni make it reference your
Postnumber

2022-02-16 06:27 UTC, JonasAls89 commented on patterns.rst
> +emit_children.
ref links her og.

2022-02-21 07:46 UTC, JonasAls89 requested changes

2022-02-21 07:46 UTC, JonasAls89 commented on patterns.rst
> +Hardhoded dataset with manually connected ids, could also be an external source with manual input. Linking table.
Type? Hardcoded dataset..

2022-02-21 11:27 UTC, JonasAls89 commented on patterns.rst
> +Hardhoded dataset with manually connected ids, could also be an external source with manual input. Linking table.
typo*

2022-02-25 12:29 UTC, BaardBouvet commented on patterns.rst
> +Hardhoded dataset with manually connected ids, could also be an external source with manual input. Linking table.
You've fixed this in a later PR, so I'll ignore this for now.

2022-02-25 12:47 UTC, branislavjenco approved these changes

2022-02-25 13:18 UTC, merged