#442 : Adding section
datanav/docs pull request #515
Opened 2021-12-21 08:21 UTC by JonasAls89

2022-01-13 16:01 UTC, ga-hegsvold requested changes

2022-01-13 16:01 UTC, ga-hegsvold commented on training/030_dtl/030_Novice.rst
> +In general, reserved fields are used in order to make Sesam perform as intended and so they will largely affect the performance of a Sesam node without you even knowing. Albeit, you will immediately
If we are to dive into details about these _ properties, I agree that the three you cover here are the most relevant.
Maybe we should also say something about in which situations these properties are encountered.
For example when using ``["filter"]`` you will see `_filtered: true` only in the result view of the pipe preview, and only if the current entity is filtered out.
After running the pipe, the same entity will be `_deleted: true` in the output dataset, but you will **not** see `_filtered` there.

Are there situations where an entity will actually have the `_filtered` property in a dataset?
I can only find it documented under the `filter` function in the DTL Guide.

2022-01-14 07:16 UTC, JonasAls89 commented on training/030_dtl/030_Novice.rst
> +``_`` properties in Sesam are categorized as `reserved fields <https://docs.sesam.io/entitymodel.html#reserved-fields>`_. These fields provide different functionality for Sesam with regards to how en
fixed

2022-01-14 07:17 UTC, JonasAls89 commented on training/030_dtl/030_Novice.rst
> +Below, a complete list of these fields is provided:
think it's so brief, and seems to me like a good entry for the section... I'll keep it for now, a bit repetitiveness might consolidate the message.. ;)

2022-01-14 11:28 UTC, ga-hegsvold requested changes

2022-01-14 11:28 UTC, ga-hegsvold commented on training/030_dtl/030_Novice.rst
> +In addition, ``_deleted`` is also used as a filter in your endpoint pipes, as you have to ensure that no deleted entities are exposed to the outside world.
The current wording of this sentence implies that you always need to filter out deleted entities in endpoints.
This is sometimes true, but not always. Sometimes the sink type handles this for you. Other times you may want deleted entities to be exported.
I think the sentence should be rephrased a bit to reflect this.

2022-01-14 11:30 UTC, ga-hegsvold requested changes
I also think it's worth mentioning that user-defined _ properties can serve as temp properties.

2022-01-17 09:20 UTC, merged