521 : 📝
datanav/docs pull request #528
Opened 2022-01-06 08:44 UTC by JonasAls89

2022-01-06 09:05 UTC, ga-hegsvold requested changes

2022-01-06 09:05 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/030_Novice.rst
> +The folder ``my-project-directory/`` will be your root folder. You will typically give this folder a name specific to the project and environment you are working on, i.e: ``sesam-development/``. In g
The different environments should not have their own folder structure.
Differences in environments should be handled by using environment config files put in the `variables/` folder.

2022-01-06 09:33 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/030_Novice.rst
> +The folder ``my-project-directory/`` will be your root folder. You will typically give this folder a name specific to the project and environment you are working on, i.e: ``sesam-development/``. In g
I'll correct. 👍

2022-01-06 14:38 UTC, ga-hegsvold requested changes
Got a few comments and questions :-)

2022-01-06 14:38 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/030_Novice.rst
> +  - consists of global and local configuration files
Can you elaborate a bit on global vs local config files? Not sure I understand the global-part.
Reading on I think maybe you're referring to `node-metadata.conf.json`? So global meaning global config for a particular Sesam node, right?

2022-01-06 14:38 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/030_Novice.rst
> +::
Add a newline here to get proper formatting of the file structure below.

2022-01-06 14:38 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/030_Novice.rst
> +The folder ``my-project-directory/`` will be your root folder. You will typically give this folder a name specific to the project you are working on, i.e: ``sesam/``. In general, it is recommended to
To ensure proper CI/CD workflow we also recommend a dedicated CI node. This is usually a Developer type node (ref _Subscriptions > Products > Choose environment_ inside Sesam).

In general we also recommend that each developer has their own Developer type node, but not sure if that is relevant to mention here.

LICENSE and .gitignore I suppose can be fairly generic, but README.md is usually project specific.
Maybe I'm misunderstanding the intention behind the use of "generic" here?

2022-01-06 14:38 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/030_Novice.rst
> +The ``expected/`` folder has to be created when first downloading the node config via the Sesam-CLI. This approach is described in detail here :ref:`sesam-cli-4-1`. The ``expected/`` folder is used a
The explanation of the expected/ folder I think can be simplified. Maybe something like:
The `expected/` folder is where all expected outputs from endpoint pipes are stored. These are used by the Sesam-CLI and CI/CD workflows to verify correct outputs.

2022-01-07 09:34 UTC, ga-hegsvold requested changes

2022-01-07 09:34 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/030_Novice.rst
> +  - consists of global configuration files and local configuration files
Do we need to distinguish between global and local configs?
Or can we just say that it consists of all configuration files for the Sesam node?

2022-01-07 09:34 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/030_Novice.rst
> +    | | ├ CI-test.json
I might have been unclear in my comment regarding the CI node.
We don't usually have a separate env.var file for CI. We use the same env.vars as for local dev node.
Ref the `test-env.json` file (default file name the Sesam CLI looks for) that in this example would resides in the `node/` folder (not under `node/variables/`).
Just noticed now that `test-env.json` is missing.

So `CI-test.json` can be removed from `node/variables/ `and `test-env.json` can be added to `node/`.

2022-01-10 13:31 UTC, ga-hegsvold approved these changes

2022-01-10 13:32 UTC, merged