522
datanav/docs pull request #534
Opened 2022-01-13 12:31 UTC by JonasAls89

2022-01-17 14:39 UTC, ga-hegsvold requested changes
How much of the CI/CD setup should this section cover?
The autodeployer is mostly explained, which is good, but not sufficient for the reader to set up CI/CD by themselves.
Thoughts?

It's might also be worth point out that CI/CD can be set up in multiple ways for a Sesam project, but what is described here are Sesam's recommendations.

2022-01-17 14:39 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/030_Novice.rst
> +Building upon the knowledge you just acquired reading the above section :ref:`node-config-4-2` is should now be obvious to you that Sesam advocate working in a CI/CD workflow.
> is should now be obvious to you

I think we should be careful with using words such as 'obvious'. If it indeed was obvious, would we even need to mention it?

Oh, and a typo: "is" --> "it"

2022-01-17 14:39 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/030_Novice.rst
> +placed in the ``variables/`` folder, should be used when the Github Autodeployer automatically uploads an updated node config to your Sesam node as you push changes via the Sesam CLI towards GitHub.
This is a very long sentence.
When describing different parameters and similar things, as a general rule I recommend we give each a separate paragraph. This makes it much easier for the reader to distinguish between the different things being described and to find what is relevant at a glance.

2022-01-17 14:39 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/030_Novice.rst
> +The ``GIT_REPO`` is equivalent to your root project folder,
``GIT_REPO`` must contain the link to the git repo where the project's Sesam configuration resides.

2022-01-17 14:39 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/030_Novice.rst
> +placed in the ``variables/`` folder, should be used when the Github Autodeployer automatically uploads an updated node config to your Sesam node as you push changes via the Sesam CLI towards GitHub.
> placed in the ``variables/`` folder,

This is redundant. As we can se from the example above, the path to the variables file must be specified, so it does not have to be in the `variables/` folder.

2022-01-17 14:39 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/030_Novice.rst
> +placed in the ``variables/`` folder, should be used when the Github Autodeployer automatically uploads an updated node config to your Sesam node as you push changes via the Sesam CLI towards GitHub.
> as you push changes via the Sesam CLI towards GitHub

I don't think this is relevant when describing how the autodeployer works. Changes can be pushed to github (or whatever VCS is used) in various ways. The autodeployer does not care how.

2022-01-18 06:42 UTC, JonasAls89 commented
> How much of the CI/CD setup should this section cover? The autodeployer is mostly explained, which is good, but not sufficient for the reader to set up CI/CD by themselves. Thoughts?
> 
> It's might also be worth point out that CI/CD can be set up in multiple ways for a Sesam project, but what is described here are Sesam's recommendations.

I'm not completely sure how to answer/resolve the above. As I link in the section to Beginner -> Sesam CLI I think the theory for setting up the CI/CD workflow in Sesam is covered. Don't you agree?

2022-01-18 06:43 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/030_Novice.rst
> +Building upon the knowledge you just acquired reading the above section :ref:`node-config-4-2` is should now be obvious to you that Sesam advocate working in a CI/CD workflow.
implemented

2022-01-18 06:43 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/030_Novice.rst
> +placed in the ``variables/`` folder, should be used when the Github Autodeployer automatically uploads an updated node config to your Sesam node as you push changes via the Sesam CLI towards GitHub.
split it up as suggested.

2022-01-18 06:43 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/030_Novice.rst
> +The ``GIT_REPO`` is equivalent to your root project folder,
implemented

2022-01-18 06:43 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/030_Novice.rst
> +placed in the ``variables/`` folder, should be used when the Github Autodeployer automatically uploads an updated node config to your Sesam node as you push changes via the Sesam CLI towards GitHub.
removed

2022-01-18 06:44 UTC, JonasAls89 commented on training/040_projects_and_infrastructure/030_Novice.rst
> +placed in the ``variables/`` folder, should be used when the Github Autodeployer automatically uploads an updated node config to your Sesam node as you push changes via the Sesam CLI towards GitHub.
removed

2022-01-19 08:31 UTC, gabriellsesam requested changes
Minor change; we should explain what CI/CD is the abbreviation for  (Continuous integration/ Continuous  deployment)

2022-01-19 09:34 UTC, JonasAls89 commented
> Minor change; we should explain what CI/CD is the abbreviation for (Continuous integration/ Continuous deployment)

This is explained in previous section. :ref:sesam-cli-4-1, therefore I think it would be redundant to explain again?

2022-01-19 13:22 UTC, gabriellsesam approved these changes
> > Minor change; we should explain what CI/CD is the abbreviation for (Continuous integration/ Continuous deployment)
> 
> This is explained in previous section. :ref:sesam-cli-4-1, therefore I think it would be redundant to explain again?

Agreed

2022-01-19 14:10 UTC, ga-hegsvold requested changes

2022-01-19 14:10 UTC, ga-hegsvold commented on training/040_projects_and_infrastructure/030_Novice.rst
> +This microservice connects to the GitHub API and integrates with a node config, as described in :ref:`node-config-4-2`, shared via GitHub.
Reading this sentence it sounds like the referenced section (node-config-4-2) explains how the GitHub API and integrates with a node config. That is not really the case, is it? The referenced section explains a typical folder structure for a node config.
I think this reference can be removed.

2022-01-19 15:21 UTC, ga-hegsvold approved these changes

2022-01-19 16:03 UTC, merged