Update 020_Beginner.rst
datanav/docs pull request #540
Opened 2022-01-21 07:50 UTC by JonasAls89

2022-01-27 15:29 UTC, gabriellsesam requested changes
Very nice, but I found some grammar mistakes after changing certain words and some sentences need to be restructured, along with a tiny bit of formatting.

2022-01-27 15:29 UTC, gabriellsesam commented on training/030_dtl/020_Beginner.rst
> +  - has an associated **pump** that pulls data from the **source**, pushes them through any **transforms**, and sends the results to the **sink**
pushes ~~them~~ it through

2022-01-27 15:29 UTC, gabriellsesam commented on training/030_dtl/020_Beginner.rst
> +**pump** that pull data from the **source**, push them through
pushes ~~them~~ it through

2022-01-27 15:29 UTC, gabriellsesam commented on training/030_dtl/020_Beginner.rst
> +functions this is implicit, like ["copy"] and ["rename"]. For other DTL
```
["copy"] and ["rename"]
```
->
```
``["copy"]`` and ``["rename"]``
```

2022-01-27 15:29 UTC, gabriellsesam commented on training/030_dtl/020_Beginner.rst
> +DTL transform. To exemplify, look at the below flow from source to pipe configuration and then to output.
```
The simplest DTL transforms only copy or rename a subset of the fields
 from the source entity that flows from source into  DTL transform. 
To exemplify, look at the below flow from source to pipe configuration and then to output.
```
->
```
The simplest DTL transforms only copies or renames a subset of
the fields from the source entity.
To exemplify, look below at how an entity flows internally in a
pipe; read from the source, processed in the transform and sent to the output.
```

2022-01-28 06:34 UTC, JonasAls89 commented on training/030_dtl/020_Beginner.rst
> +DTL transform. To exemplify, look at the below flow from source to pipe configuration and then to output.
Thanks for the above feedback. Was good! Albeit, this last one should stay as plural, since "transforms" dictate copy and rename.

2022-01-28 09:54 UTC, gabriellsesam approved these changes

2022-01-28 10:50 UTC, merged