Rewrite Architecture & Concepts: Beginner
datanav/docs pull request #565
Opened 2022-02-03 08:47 UTC by gabriellsesam

2022-02-04 07:05 UTC, JonasAls89 requested changes
Bra start her!

En del ting som må fikses:

Alle screenshots av noden må oppdaters. "Datasets" tabben vises, og det er outdated.

Naming convention og screenshots på alle steg i et Sesam dataflow må oppdaters. Inkluderer ikke -raw steget. 

Husk å sjekke at Summary har heading og ordentlig indented, slik det renders korrekt.

2022-02-04 07:05 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
> +  The sesam Portal allows you to:
Syntax må fikses her, ser ikke riktig ut når man kikker på summary i browser her, etter å ha bygget docs

2022-02-04 07:05 UTC, JonasAls89 commented on training/010_architecture_and_concepts/020_Beginner.rst
>  .. figure:: ./media/Architecture_Beginner_The_Sesam_Portal_B.png
Bildet her må oppdateres. Tab med "Dataset" vises fortsatt her. Det er outdated.

2022-03-30 09:01 UTC, BaardBouvet commented
This is just noise as the training branch is dead

2022-03-30 09:01 UTC, closed without merging