Changing naming convention
datanav/docs pull request #572
Opened 2022-02-08 08:12 UTC by JonasAls89

2022-02-08 08:17 UTC, BaardBouvet requested changes
Isn't it supposed to be called "-collect", "-enrich", etc?

2022-02-11 09:50 UTC, BaardBouvet requested changes

2022-02-11 09:50 UTC, BaardBouvet commented on demo-config/pipes/organisation-classification-synapse-share.conf.json
> +      "allow_nul": false,
What is this?

2022-02-11 09:50 UTC, BaardBouvet commented on demo-config/systems/github-autodeployer.conf.json
> +      "SYNC_ROOT": "demo-config"
This microservice should not be part of the config at all, you don't want this during development.

2022-02-11 09:50 UTC, BaardBouvet commented on demo-config/pipes/nace-code-enrich.conf.json
> +{
We don't need enrich pipes for the RDF stuff do we?

2022-02-11 09:50 UTC, BaardBouvet commented on demo-config/pipes/difi-enhetsregisteret-enrich-classification.conf.json
> +  "_id": "difi-enhetsregisteret-enrich-classification",
This pipe could just be called difi-enhetsregisteret-classification

2022-02-11 09:50 UTC, BaardBouvet commented on demo-config/node-metadata.conf.json
> +      "zem": "http://s.zemanta.com/ns#"
Why was this suddenly reordered?

2022-02-11 10:08 UTC, JonasAls89 commented on demo-config/pipes/organisation-classification-synapse-share.conf.json
> +      "allow_nul": false,
fixed

2022-02-11 10:09 UTC, JonasAls89 commented on demo-config/systems/github-autodeployer.conf.json
> +      "SYNC_ROOT": "demo-config"
Not sure what you want me to do here...? It is not working locally (in development), as I don't have any of the $ENV or $SECRET variables.

2022-02-11 10:10 UTC, JonasAls89 commented on demo-config/pipes/difi-enhetsregisteret-enrich-classification.conf.json
> +  "_id": "difi-enhetsregisteret-enrich-classification",
fixed

2022-02-11 10:10 UTC, JonasAls89 commented on demo-config/node-metadata.conf.json
> +      "zem": "http://s.zemanta.com/ns#"
no idea.

2022-02-11 10:14 UTC, BaardBouvet commented on demo-config/systems/github-autodeployer.conf.json
> +      "SYNC_ROOT": "demo-config"
Remove the github-autodeployer from this repo. The microservices is just added directly in production systems as far as I know.

2022-02-11 10:15 UTC, BaardBouvet commented on demo-config/node-metadata.conf.json
> +      "zem": "http://s.zemanta.com/ns#"
Maybe the first version was exported from the UI, but this was done using the sesam-py tool?

2022-02-11 10:16 UTC, BaardBouvet commented on demo-config/systems/github-autodeployer.conf.json
> +      "SYNC_ROOT": "demo-config"
Let's remove it in a separate PR. It's not really about naming conventions.

2022-02-11 10:17 UTC, BaardBouvet commented on demo-config/pipes/hubspot-company-enrich-classification.conf.json
> +  "_id": "hubspot-company-enrich-classification",
This should also be renamed to hubspot-company-classification

2022-02-11 10:20 UTC, JonasAls89 commented on demo-config/node-metadata.conf.json
> +      "zem": "http://s.zemanta.com/ns#"
true.

2022-02-11 10:23 UTC, JonasAls89 commented on demo-config/pipes/hubspot-company-enrich-classification.conf.json
> +  "_id": "hubspot-company-enrich-classification",
fixed

2022-02-11 10:30 UTC, BaardBouvet requested changes

2022-02-11 10:30 UTC, BaardBouvet commented on demo-config/pipes/classification-synapse-share.conf.json
> +  "_id": "classification-synapse-share",
Is the naming convention correct here? "system-datatype-\<step\>"?

2022-02-11 10:35 UTC, JonasAls89 commented on demo-config/pipes/classification-synapse-share.conf.json
> +  "_id": "classification-synapse-share",
I believe so yea. I.e: for hubspot outbound flow (<datatype-system>), it is: company-hubspot-transform -> company-hubspot-update-share.

We can omit "update" or "insert" here because we only have one -share flow for classification-synapse.

2022-02-14 07:53 UTC, JonasAls89 commented on demo-config/pipes/classification-synapse-share.conf.json
> +  "_id": "classification-synapse-share",
Oppdatert.

2022-02-17 07:44 UTC, BaardBouvet approved these changes

2022-02-17 07:46 UTC, merged