Update patterns.rst
datanav/docs pull request #594
Opened 2022-03-03 11:46 UTC by JonasAls89

2022-03-03 11:50 UTC, BaardBouvet requested changes

2022-03-03 11:50 UTC, BaardBouvet commented on patterns.rst
> +Subsets
I think we should call it "Only process the relevant entities from a global using subset"

2022-03-03 11:50 UTC, BaardBouvet commented on patterns.rst
> +If your source supports it, you should use the :ref:`subset <dataset_source>` property to pick subsets of a complete dataset, i.e: after a merge source has been used upstream.
The global will always support subsets, so this is irrelevant.

2022-03-04 06:52 UTC, JonasAls89 commented
Trying to sum up on the 50 plus threads about this. Let me know if something should be restated.

2022-03-04 07:31 UTC, grove commented on patterns.rst
> +  This pattern is sensitive to multiple versions of the entity id in one complete pipe run, i.e: if entities move between subsets, then you need to deal with these moves, as they will create old enti
I don’ think we should call it move between subsets.  An entity can be part of many subsets at the same time. It is more about an entity being added to a subset and then later removed from it. Just the same was as an entity is added to dataset and then later removed from it.

2022-03-09 08:40 UTC, BaardBouvet requested changes

2022-03-09 08:40 UTC, BaardBouvet commented on patterns.rst
> +Therefore, you should materialise the subset in a separate dataset before “picking” your derived entities using subset to minimise the risk of creating entities that are not in the latest versions of
When thinking about it, why would anyone then use subset to extract entities? The pattern we should describe is "How to extract entities", which is about using create and full scan to remove orphans. We can mention that subsets can't be used for this, and the solution is to just use filtering instead.

2022-03-09 11:27 UTC, JonasAls89 commented on patterns.rst
> +Therefore, you should materialise the subset in a separate dataset before “picking” your derived entities using subset to minimise the risk of creating entities that are not in the latest versions of
Implemented

2022-03-09 14:13 UTC, BaardBouvet requested changes

2022-03-09 14:13 UTC, BaardBouvet commented on patterns.rst
> +In general, using :ref:`subset <dataset_source>` to extract entities is straight forward. Albeit, edge cases do exist. In example, if you use the :ref:`create <dtl-transforms>` and :ref:`subset <data
The only way to extract entities is to use create, so this still needs a rewrite I think.

2022-03-09 14:21 UTC, JonasAls89 commented on patterns.rst
> +In general, using :ref:`subset <dataset_source>` to extract entities is straight forward. Albeit, edge cases do exist. In example, if you use the :ref:`create <dtl-transforms>` and :ref:`subset <data
Changed it.

2022-03-09 14:30 UTC, BaardBouvet approved these changes

2022-03-09 14:38 UTC, merged