Microservices
datanav/docs pull request #632
Opened 2022-03-24 10:49 UTC by erik-leven

Added a section in User Guide -> Data synchronization about microservices.

Update Learn -> Data synchronizaiton -> Microservices

2022-03-24 11:04 UTC, JonasAls89 submitted a review, later dismissed

2022-03-24 11:04 UTC, JonasAls89 commented on tutorial-microservice-continuation-support.rst
> +      return
blank return? Is this intended for the exercise?

2022-03-24 11:30 UTC, erik-leven commented on tutorial-microservice-continuation-support.rst
> +      return
Yes, it's intended. But I see now that the last changes I did to this specific tutorial are not included. I'll fix them during the day

2022-03-31 09:42 UTC, BaardBouvet commented on guide-developer-extension-points.rst
> +        There are a number of starter service implementations that can be copied and changed. These are open source and can be cloned from the `Sesam open source repository <https://www.github.com/se
I think we should link to the community page in docs here, that page has a link to this repo but with more context.

2022-03-31 09:44 UTC, BaardBouvet commented on tutorial-microservice-continuation-support.rst
> +An IT consultant company wishes to create an automated CV functionality for all of their employees and publish it on their website. As part of their CV the company want to display all the code reposi
The baseline should be the demo with hubspot, so we should tie this tutorial to that.

2022-03-31 09:45 UTC, BaardBouvet commented on tutorial-custom-data-source-microservice.rst
> +An IT consultant company wishes to create an automated CV functionality for all of their employees and publish it on their website. As part of their CV the company want to display all the code reposi
This is repeated in both tutorials, we should find a way to avoid that.

2022-03-31 09:55 UTC, BaardBouvet requested changes

2022-03-31 09:55 UTC, BaardBouvet commented on extension-points.rst
> +*************************************
I don't think REST transform is considered an extension point either.

2022-03-31 10:00 UTC, erik-leven commented on guide-developer-extension-points.rst
> +        There are a number of starter service implementations that can be copied and changed. These are open source and can be cloned from the `Sesam open source repository <https://www.github.com/se
Yeah, that sounds like a better alternative

2022-03-31 10:02 UTC, erik-leven commented on tutorial-custom-data-source-microservice.rst
> +An IT consultant company wishes to create an automated CV functionality for all of their employees and publish it on their website. As part of their CV the company want to display all the code reposi
Agreed

2022-03-31 10:02 UTC, erik-leven commented on extension-points.rst
> +*************************************
Se comment above

2022-03-31 10:03 UTC, erik-leven commented on extension-points.rst
> +There are many native Sesam components for collecting, transforming and using data. Sometimes however, there might be a need for :ref:`source <source_section>`, :ref:`transform <transform_section>` o
Hmm, yeah that could be a good idea. Would make it easier to locate what you're looking for

2022-03-31 10:08 UTC, BaardBouvet commented on extension-points.rst
> +Custom Data Source - The REST system
JSON push or JSON pull are our protocols, we don't expect anyone else to support that.

2022-03-31 10:17 UTC, BaardBouvet commented on tutorial-microservice-continuation-support.rst
> +  from flask import Flask, request
Same here, don't repeat ourselves. Pointing to the Github template solves this problem.

2022-04-11 12:31 UTC, erik-leven commented on tutorial-microservice-continuation-support.rst
> +  from flask import Flask, request
I think "don't repeat" is a good main line, but not always the right answer.

2022-04-11 12:31 UTC, erik-leven commented on tutorial-microservice-continuation-support.rst
> +An IT consultant company wishes to create an automated CV functionality for all of their employees and publish it on their website. As part of their CV the company want to display all the code reposi
Done

2022-04-11 12:50 UTC, BaardBouvet requested changes

2022-04-11 12:50 UTC, BaardBouvet commented on custom-data-transform.rst
> +Creating a Custom Transform
Missing link to tutorial

2022-04-11 12:50 UTC, BaardBouvet commented on extension-points.rst
> +There are many native Sesam components for collecting, transforming and using data. Sometimes however, there might be a need for :ref:`source <source_section>`, :ref:`transform <transform_section>` o
enterprice is written enterprise, but why introduce this new word? Just write "to cover all the needs".

2022-04-11 12:50 UTC, BaardBouvet commented on extension-points.rst
> +These connections can be used to configure either a :ref:`custom data source <custom_data_source>`, a :ref:`custom transform <custom_transform>` or a :ref:`cystom data sink <custom_data_sink>`.
Typo, should be cystom->custom

2022-04-11 12:50 UTC, BaardBouvet commented on custom-data-source.rst
> +    .. link-button:: tutorial-custom-data-source-microservice.html
Wrong link, also use ref type of links to make sure sphinx checks that the document exists

2022-04-11 12:54 UTC, erik-leven commented on custom-data-sink.rst
> +Creating a Custom Data Sink
fixed

2022-04-11 12:54 UTC, erik-leven commented on custom-data-transform.rst
> +Creating a Custom Transform
fixed

2022-04-11 12:55 UTC, erik-leven commented on extension-points.rst
> +There are many native Sesam components for collecting, transforming and using data. Sometimes however, there might be a need for :ref:`source <source_section>`, :ref:`transform <transform_section>` o
Made the sentence flow better, but can be removed

2022-04-11 12:57 UTC, erik-leven commented on custom-data-source.rst
> +    .. link-button:: tutorial-custom-data-source-microservice.html
fixed

2022-04-11 12:57 UTC, erik-leven commented on custom-data-sink.rst
> +Just as with the :ref: `Custom Data Source <custom_data_source>` and the :ref: `Custom Transform <custom_transform>` you need to define a system (such as the :ref: `HTTP system <http_system>` or the
fixed

2022-04-11 13:10 UTC, BaardBouvet submitted a review, later dismissed

2022-04-11 13:11 UTC, erik-leven commented on extension-points.rst
> +Custom Data Source - The REST system
fixed

2022-04-11 13:22 UTC, erik-leven commented on custom-data-source.rst
> +Logs from a microservice
Done

2022-04-21 07:18 UTC, grove commented on json-push.rst
> +
It is not necessary to add anchors if you just want to link to the document. Use the :doc: type link to link to documents.

2022-04-21 07:27 UTC, grove commented on tutorial-custom-data-source-microservice.rst
> +.. admonition:: Prerequisits
typo: Prerequisits

2022-04-21 09:04 UTC, erik-leven commented on json-push.rst
> +
Fixed

2022-04-21 09:04 UTC, erik-leven commented on tutorial-custom-data-source-microservice.rst
> +.. admonition:: Prerequisits
Fixed

2022-04-21 14:34 UTC, grove commented on tutorial-custom-data-source-microservice.rst
> +  Testing how a microservice interacts with Sesam directly in Sesam can be troublesome as you have to create a Docker image and spin up the corresponding container in Sesam for each code change. Make
typo: thouroughly

2022-04-21 14:35 UTC, grove commented on tutorial-custom-data-source-microservice.rst
> +When the Docker image has been created and hosted online we can connect it to a :ref:`Microservice system <microservice_system>` in Sesam and spin up the container. We do this by declaring where wher
double: where where

2022-04-21 14:37 UTC, grove commented on tutorial-custom-data-source-microservice.rst
> +We also wish to copy all the data imported and save it to the pipe's resulting dataset. This is done by the ``["copy", "*"]`` transformation..
Double punctuation.

2022-04-21 14:39 UTC, grove commented on tutorial-microservice-continuation-support.rst
> +    - Each API has different functionalities, and not every API supports query parameters to only access updated data. It's important to throuroughly read the API's documentation in order to set the
typo: throuroughly

2022-04-21 14:46 UTC, grove requested changes
Added a few comments that should be fixed, but other than those this looks great.

2022-04-21 14:52 UTC, erik-leven commented on tutorial-microservice-continuation-support.rst
> +        "cron_expression": "0 0 ? * *"
fixed

2022-04-21 14:52 UTC, erik-leven commented on tutorial-microservice-continuation-support.rst
> +    - Each API has different functionalities, and not every API supports query parameters to only access updated data. It's important to throuroughly read the API's documentation in order to set the
fixed

2022-04-21 14:52 UTC, erik-leven commented on tutorial-custom-data-source-microservice.rst
> +  Testing how a microservice interacts with Sesam directly in Sesam can be troublesome as you have to create a Docker image and spin up the corresponding container in Sesam for each code change. Make
fixed

2022-04-21 14:57 UTC, grove approved these changes

2022-04-22 06:25 UTC, merged