Guide layout
datanav/docs pull request #656
Opened 2022-03-31 13:53 UTC by djalil-bouhachi

<img width="890" alt="Guide-layout" src="https://user-images.githubusercontent.com/83338638/161071695-4bdc04c2-0805-498e-958c-25a0f9b8f83e.PNG">

2022-03-31 19:40 UTC, BaardBouvet commented
Perhaps we should add some time estimates for the tutorials? 30 minutes, etc.

2022-03-31 19:41 UTC, BaardBouvet requested changes

2022-03-31 19:41 UTC, BaardBouvet commented on Guide-template.rst
> +   * Get familar with concepts
These should be links

2022-03-31 19:41 UTC, BaardBouvet commented
I think this looks great, see my comments on the review!

2022-04-04 08:15 UTC, djalil-bouhachi commented on Guide-template.rst
> +   * Get familar with concepts
OK

2022-04-04 08:16 UTC, djalil-bouhachi commented
@BaardBouvet Added 2 ways to show reading time estimates. 
![Guide layout](https://user-images.githubusercontent.com/83338638/161502687-ef83c09d-be95-4e6c-aa6f-e01dcf03321f.PNG)

2022-04-04 08:18 UTC, djalil-bouhachi commented
Added 2 ways to show estimated reading time @BaardBouvet 
![Guide layout](https://user-images.githubusercontent.com/83338638/161502985-ececbd01-3968-47a2-bce0-49d75a9158d8.PNG)

2022-04-26 09:12 UTC, closed without merging