adding draft to structure
datanav/docs pull request #672
Opened 2022-04-06 13:27 UTC by JonasAls89

**Do not merge** as also labelled.

Djalil what do you think about this structure. In accordance to how you would like it to be?

2022-04-22 12:28 UTC, erik-leven commented on guide-collect.rst
> +   #. Learned about Sesam's source systems and created one
The first and second line (source system and inbound) should maybe have a similar text? Vi mangler f.eks. "learn about" input pipes

2022-04-22 12:28 UTC, erik-leven commented on guide-collect.rst
> +   #. Configured its pump and verified a populated sink
sink dataset?

2022-04-22 12:29 UTC, erik-leven commented on guide-collect.rst
> +   #. Learned about Sesam's source systems and created one
Link?

2022-04-22 12:29 UTC, erik-leven commented on guide-collect.rst
> +   #. Configured its pump and verified a populated sink
Link?

2022-04-22 12:29 UTC, erik-leven commented on guide-collect.rst
> +   #. Tested data change tracking
Link?

2022-04-22 12:29 UTC, erik-leven commented on guide-collect.rst
> +   #. Learned about Sesam's generic data model
link

2022-04-22 12:30 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +
Introduksjon?

2022-04-22 12:31 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +When a System is used as a source it is especially important to recognize that providing streams of entities as these are updated in the source system as a :ref:`delta stream <delta-stream-processing
System -> system

2022-04-22 12:32 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +When a System is used as a source it is especially important to recognize that providing streams of entities as these are updated in the source system as a :ref:`delta stream <delta-stream-processing
missing a comma after "... providing streams of entities"

2022-04-22 12:32 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +When a System is used as a source it is especially important to recognize that providing streams of entities as these are updated in the source system as a :ref:`delta stream <delta-stream-processing
First sentence is very long

2022-04-22 12:33 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +When a System is used as a source it is especially important to recognize that providing streams of entities as these are updated in the source system as a :ref:`delta stream <delta-stream-processing
Last sentence has a lot of commas

2022-04-22 13:20 UTC, JonasAls89 commented on guide-collect.rst
> +   #. Learned about Sesam's source systems and created one
fixed

2022-04-22 13:20 UTC, JonasAls89 commented on guide-collect.rst
> +   #. Configured its pump and verified a populated sink
changed

2022-04-22 13:23 UTC, JonasAls89 commented on guide-collect.rst
> +   #. Learned about Sesam's source systems and created one
fixed

2022-04-22 13:38 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +Sesam supports implementing multiple types of :ref:`systems <system_section>`, i.e: JSON, SQL, microservice etc. Each system, regardless of type, will have a defined set of implementation functionali
hmm, maybe link to JSON, SQL and microservice instead of systems? 
The introduktion should contain some information about the tutorial, right now it's just very general. I.e. "in this tutorial we will look closer into Source systems in Sesam......."

2022-04-22 13:40 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +When a system is used as a source it is especially important to recognize that providing streams of entities as these are updated in the source system as a :ref:`delta stream <delta-stream-processing
missing comma after "... providing streams of entities"
many commas in last sentence, hard to read?

2022-04-22 13:41 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +Sesam supports implementing multiple types of :ref:`systems <system_section>`, i.e: JSON, SQL, microservice etc. Each system, regardless of type, will have a defined set of implementation functionali
We say nothing of what a source system is. Right now the focus is systems in general

2022-04-22 13:42 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +  #. You should have completed the :ref:`getting started guide <getting-started>` before starting on this tutorial.
If we use this as a prerequisite, we will need to use it in all tutorials we make

2022-04-22 13:44 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +The source system you will be working with in this tutorial is `HubSpot <https://www.hubspot.com/>`_. You will connect to the HubSpot API in Sesam with the use of the system type :ref:`REST <rest_sou
This is not a source system, this is a service we connect a source system to. Else we will need to define a difference between a source system in Sesam and a source system outside Sesam

2022-04-22 13:47 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +#. Add your system secret ``hubspot-jwt`` in the Secrets tab, as highlighted in the code below
should we mention that hubspot-jwt = API key from above? Also, Is the API key is a jwt? Haven't looked close at it

2022-04-25 06:59 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +#. Select the subscription you want to work on
I think these steps might be too much. Again, every tutorial would need these steps. Should we remove log in and select subscription?

2022-04-25 07:53 UTC, JonasAls89 commented on tutorial-collect-source-systems.rst
> +#. Select the subscription you want to work on
Will implement

2022-04-25 07:53 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +  #. You should have completed the :ref:`getting started guide <getting-started>` before starting on this tutorial.
Wouldn't it make more sense to put that in the guide? Make sure you have completed "getting started" before the other tutorials?

2022-04-25 08:45 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +#. Add your system secret ``hubspot-jwt`` in the Secrets tab, as highlighted in the code below
I agree we don't have to talk too much about it, but it would be nice to state stat that secret refers to the API key. I would also like to change the secret name, seeing as this is not a JWT. Maybe just "hubspot-api-key"?

2022-04-25 09:30 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +The system you will be working with in this tutorial is `HubSpot <https://www.hubspot.com/>`_. You will connect to the HubSpot API in Sesam with the use of the system type :ref:`REST <rest_source>` a
Hmmm, we're normally referring to Sesam systems when we say "system". Now you're referring to an external provider. We should clarify this. Is hubspot actually a system or is it a provider?

2022-04-25 09:30 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +The system you will be working with in this tutorial is `HubSpot <https://www.hubspot.com/>`_. You will connect to the HubSpot API in Sesam with the use of the system type :ref:`REST <rest_source>` a
Looks like you're still using the old HubSpot API. Is that the plan?

2022-04-25 09:33 UTC, erik-leven commented on tutorial-collect-source-systems.rst
> +          Yes they can.
(as long at the stream exposes a json array)

2022-05-25 08:02 UTC, JonasAls89 commented on tutorial-collect-source-systems.rst
> +          Yes they can.
corrected

2022-05-25 12:15 UTC, ga-hegsvold requested changes
See comments.

2022-05-25 12:24 UTC, ga-hegsvold requested changes

2022-05-25 12:24 UTC, ga-hegsvold commented on guide-collect.rst
> +   #. Made required data transformation in your recently created inbound pipe
Should data transformations be covered at a later stage considering we want to do raw imports?
Or is this perhaps to cover cases where ``_id`` must be added with DTL?

2022-05-31 11:52 UTC, erik-leven commented on guide-collect.rst
> +    **Collect:** This guide includes 7 tutorials
Previously we've only counted un-commented tutorials

2022-06-20 07:40 UTC, closed without merging