Is 12486 alt
datanav/docs pull request #754
Opened 2022-06-17 11:13 UTC by erik-leven

Reference fix

2022-06-20 05:59 UTC, JonasAls89 approved these changes
Ser veldig bra ut @erik-leven 👍

2022-06-20 06:29 UTC, JonasAls89 requested changes
minor changes. Else looks very good!

2022-06-20 06:29 UTC, JonasAls89 commented on learn-collect-inbound-pipes.rst
> +The main difference between inbound pipes and other Sesam pipes is that inbound pipes uses Sesam systems as source of data, compared to other pipes that uses datasets as data sources. Depending on th
indbound pipes use... igjen bør det være plural under. other pipes that use datasets...

2022-06-20 06:29 UTC, JonasAls89 commented on learn-collect-inbound-pipes.rst
> +The main difference between inbound pipes and other Sesam pipes is that inbound pipes uses Sesam systems as source of data, compared to other pipes that uses datasets as data sources. Depending on th
kan bruke bare: catch all functionality. omit "the".

2022-06-20 06:29 UTC, JonasAls89 commented on learn-index-collect.rst
> +In the :ref:`collect <collect>` phase we import data into Sesam. This includes setting up the system configuration for a :doc:`Sesam system <configuration-systems>` that we wish to connect to an exte
double any... remove one. typo on conncet <- connect.

2022-06-20 06:29 UTC, JonasAls89 commented on learn-index-collect.rst
> +	In some of these tutorials we will use `HubSpot <https://www.hubspot.com/>`_ as a baseline. If you did not already created a HubSpot test account in :doc:`getting started <guide-getting-started>` we
tense deviance here. should be: If you did not already create ...

2022-06-20 06:29 UTC, JonasAls89 commented on tutorial-inbound-pipe-rest.rst
> +In this tutorial we will look closer into the creation of an :ref:`inbound pipe <best-practice-workflow>` connected to a :doc:`Sesam system <configuration-systems>`. Sesam best practices recommend to
However, this is not very uncommen.. <- missing is..

2022-06-20 06:29 UTC, JonasAls89 commented on tutorial-inbound-pipe-rest.rst
> +In this tutorial we use the ``hubspot`` system created in the :doc:`Source System - REST <tutorial-source-system-rest>` tutorial to import `contacts from HubSpot <https://developers.hubspot.com/docs/
will typo "till"

2022-06-20 06:29 UTC, JonasAls89 commented on tutorial-inbound-pipe-rest.rst
> +Before we analyze the data supplied byt the HubSpot API, we need some more contact data in HubSpot. This will make it a lot more interesting for you as you work with related tutorials down the road.
by typo "byt" first line.

2022-06-20 06:29 UTC, JonasAls89 commented on tutorial-inbound-pipe-rest.rst
> +Unless otherwise stated, the HubSpot API only provides some data in each dictionary per default unless otherwise stated. However, the API allows you to query which ever contact data you want. In our
Omit the first "unless otherwise stated" it's used double up.

2022-06-20 06:29 UTC, JonasAls89 commented on tutorial-inbound-pipe-rest.rst
> +Unless otherwise stated, the HubSpot API only provides some data in each dictionary per default unless otherwise stated. However, the API allows you to query which ever contact data you want. In our
whichever in one word.

2022-06-20 06:29 UTC, JonasAls89 commented on tutorial-source-system-rest.rst
> +When creating a REST system in Sesam there are several ways one can define the url to which we wish to send a request. In general you want to system to contain a base url to which you can connect end
typo on "with" should be ... on which API a specific pipe wishes to ...

2022-06-20 06:29 UTC, JonasAls89 commented on tutorial-source-system-rest.rst
> +Since we still haven't access any specific API, the only result we can check at this time is whether or not we are allowed to access the domain. This can be checked by looking at the system's status
tense deviance again: should be "accessed" in the first sentence

2022-06-20 07:21 UTC, erik-leven commented on learn-collect-inbound-pipes.rst
> +The main difference between inbound pipes and other Sesam pipes is that inbound pipes uses Sesam systems as source of data, compared to other pipes that uses datasets as data sources. Depending on th
fixed

2022-06-20 07:22 UTC, erik-leven commented on learn-index-collect.rst
> +In the :ref:`collect <collect>` phase we import data into Sesam. This includes setting up the system configuration for a :doc:`Sesam system <configuration-systems>` that we wish to connect to an exte
fixed

2022-06-20 07:22 UTC, erik-leven commented on learn-index-collect.rst
> +	In some of these tutorials we will use `HubSpot <https://www.hubspot.com/>`_ as a baseline. If you did not already created a HubSpot test account in :doc:`getting started <guide-getting-started>` we
fixed

2022-06-20 07:23 UTC, erik-leven commented on tutorial-inbound-pipe-rest.rst
> +In this tutorial we will look closer into the creation of an :ref:`inbound pipe <best-practice-workflow>` connected to a :doc:`Sesam system <configuration-systems>`. Sesam best practices recommend to
fixed

2022-06-20 07:23 UTC, erik-leven commented on tutorial-inbound-pipe-rest.rst
> +In this tutorial we use the ``hubspot`` system created in the :doc:`Source System - REST <tutorial-source-system-rest>` tutorial to import `contacts from HubSpot <https://developers.hubspot.com/docs/
fixed

2022-06-20 07:23 UTC, erik-leven commented on tutorial-inbound-pipe-rest.rst
> +Before we analyze the data supplied byt the HubSpot API, we need some more contact data in HubSpot. This will make it a lot more interesting for you as you work with related tutorials down the road.
fixed

2022-06-20 07:24 UTC, erik-leven commented on tutorial-inbound-pipe-rest.rst
> +Unless otherwise stated, the HubSpot API only provides some data in each dictionary per default unless otherwise stated. However, the API allows you to query which ever contact data you want. In our
fixed

2022-06-20 07:25 UTC, erik-leven commented on tutorial-source-system-rest.rst
> +When creating a REST system in Sesam there are several ways one can define the url to which we wish to send a request. In general you want to system to contain a base url to which you can connect end
fixed

2022-06-20 07:25 UTC, erik-leven commented on tutorial-source-system-rest.rst
> +Since we still haven't access any specific API, the only result we can check at this time is whether or not we are allowed to access the domain. This can be checked by looking at the system's status
fixed

2022-06-20 11:57 UTC, ga-hegsvold requested changes

2022-06-20 11:57 UTC, ga-hegsvold commented on learn-collect-inbound-pipes.rst
> +    - :ref:`Inbound pipes <concepts-pipes>`
The referenced section does not mention inbound pipes, just pipes, so this reference should be called "Pipes".
Do we even need to name the references here? Can we not just let the tool generate the ref names based to the referenced section titles?
```
    - :doc:`index-whatis`
    - :doc:`developer-guide`    
    - :ref:`concepts-pipes`
```

2022-06-20 11:57 UTC, ga-hegsvold commented on learn-collect-inbound-pipes.rst
> +In this guide we will look closer at :ref:`inbound pipes <concepts-pipes>` in Sesam and how they connect to :doc:`Sesam systems <configuration-systems>`.
Should probable skip the link to the Pipes section here since that section does not mention inbound pipes.

2022-06-20 11:57 UTC, ga-hegsvold commented on tutorial-inbound-pipe-rest.rst
> +#. Agree to the terms and click **Finish import**
The contacts should already be imported if the reader did the Getting Started guide.
If not I think we should just reference it. The import process is already explained in tutorial-getting-started-collect.html#import-data-to-hubspot

2022-06-20 11:57 UTC, ga-hegsvold commented on tutorial-inbound-pipe-rest.rst
> +A REST API does not necessarily provide data on the :doc:`structure Sesam prefers <entitymodel>`. It's therefore important to analyze the incoming API payload before creating the inbound pipe. By doi
Can we tighten this paragraph a bit?

A payload from a REST API is not necessarily structured the way :doc:`Sesam prefers <entitymodel>`.
It is therefore important to analyze the payload and adapt the inbound pipe accordingly.
Payload examples are often provided in the API documentation for the REST service in question.
In HubSpot's case, entities are returned as dictionaries inside a ``results`` array as shown in the example below.

2022-06-20 11:57 UTC, ga-hegsvold commented on tutorial-inbound-pipe-rest.rst
> +Unless otherwise stated, the HubSpot API only provides some data in each dictionary per default. However, the API allows you to query which ever contact data you want. In our case, we would like to a
Suggest a slight rephrasing of the first sentence in this paragraph to clarify that by default the payload only contains a few properties on each entity:
By default, HubSpot returns only a small subset of available properties on each entity.
However, the API allows you to query...

2022-06-21 08:50 UTC, erik-leven commented on learn-collect-inbound-pipes.rst
> +    - :ref:`Inbound pipes <concepts-pipes>`
Good point, and I agree. Fixed now

2022-06-21 08:55 UTC, erik-leven commented on learn-collect-inbound-pipes.rst
> +In this guide we will look closer at :ref:`inbound pipes <concepts-pipes>` in Sesam and how they connect to :doc:`Sesam systems <configuration-systems>`.
fixed

2022-06-21 08:55 UTC, erik-leven commented on tutorial-inbound-pipe-rest.rst
> +#. Agree to the terms and click **Finish import**
I've added a link to getting started collect. I don't think we can assume everyone does getting started

2022-06-21 08:56 UTC, erik-leven commented on tutorial-inbound-pipe-rest.rst
> +A REST API does not necessarily provide data on the :doc:`structure Sesam prefers <entitymodel>`. It's therefore important to analyze the incoming API payload before creating the inbound pipe. By doi
I like it

2022-06-21 08:57 UTC, erik-leven commented on tutorial-inbound-pipe-rest.rst
> +Unless otherwise stated, the HubSpot API only provides some data in each dictionary per default. However, the API allows you to query which ever contact data you want. In our case, we would like to a
done

2022-06-21 09:57 UTC, ga-hegsvold requested changes

2022-06-21 09:57 UTC, ga-hegsvold commented on tutorial-inbound-pipe-rest.rst
> +A payload from a REST API is not necessarily structured the way :doc:Sesam prefers <entitymodel>. It is therefore important to analyze the payload and adapt the inbound pipe accordingly.
Ref not working. Add missing single quotes around `"Sesam prefers <entitymodel>"`.

2023-03-28 10:36 UTC, closed without merging