making default optional explicit
datanav/docs pull request #821
Opened 2022-09-14 13:45 UTC by JonasAls89

2022-09-14 13:47 UTC, BaardBouvet requested changes
I would drop the optional word from the first sentence as well.

2022-09-14 17:06 UTC, grove approved these changes

2022-09-15 06:48 UTC, erik-leven approved these changes

2022-09-16 10:32 UTC, BaardBouvet approved these changes

2022-09-16 13:24 UTC, merged