Update durable-data.rst
datanav/docs pull request #835
Opened 2022-09-26 09:41 UTC by mellbye-Sesam

Clean Important msg. 
More consistent use of high-durability disk and clarify the use case for durable data.

2022-09-26 11:45 UTC, grove commented on features/durable-data.rst
> +For cloud subscriptions, data is backed up to an external service once every 24 hours. During a disaster recovery data written the last 24 hours can be lost. By using replicas and a high-durability d
Typo: "reduces" should be "reduced"

2022-09-26 11:47 UTC, grove commented on features/durable-data.rst
> +By enabling durable data, Sesam will store the pipe data in three replicas on a high-durability disk. This greatly reduces the likelihood of data loss.
The "three replicas" part is sort of an implementation detail and I'm not sure we have to mention that at all.

2022-09-26 11:48 UTC, grove requested changes
I've added a few comments.

2022-09-26 12:30 UTC, djalil-bouhachi approved these changes

2022-09-26 13:31 UTC, mellbye-Sesam commented on features/durable-data.rst
> +By enabling durable data, Sesam will store the pipe data in three replicas on a high-durability disk. This greatly reduces the likelihood of data loss.
agreed, will fix

2022-09-27 07:36 UTC, djalil-bouhachi approved these changes

2022-09-30 06:02 UTC, grove approved these changes

2022-10-03 06:46 UTC, merged